In [ ]:
#https://towardsdatascience.com/build-a-super-simple-gan-in-pytorch-54ba349920e4


In [242]:
import torch
import torchvision
from torchvision import transforms, datasets, models

import torch.optim as optim


import torch.nn as nn
import torch.nn.functional as F



import os 
import time
import cv2

from tqdm.notebook import tqdm
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import math

rebuild_data = False

In [2]:
if torch.cuda.is_available():
    device = torch.device("cuda: 0")
else:
    device = torch.device("cpu")
    
#i could assign specific layers to one gpu 

torch.cuda.device_count() #but i have only one :P
    

1

In [244]:
def create_binary_list_from_int(number):
    return [int(x) for x in list(bin(number))[2:]]

In [9]:
bin(4)

'0b100'

In [10]:
dec2bin(4)

[1, 0, 0]

In [220]:
def makeEvenData(max_int, batch_size = 16):
    
    max_length = int(math.log(max_int, 2))
    
    sampled_integers = np.random.randint(0, int(max_int /2), batch_size)
    
    labels = [1] * batch_size
    
    data = [create_binary_list_from_int(int(x*2)) for x in sampled_integers]
    data = [([0] * (max_length - len(x))) + x for x in data]
    
    return labels, data

In [221]:
[0]+[1,2]

[0, 1, 2]

In [222]:
np.random.rand(2)

array([0.03813136, 0.96011237])

In [223]:
np.random.randint(0, 4, 16)

array([0, 3, 3, 0, 2, 3, 2, 2, 2, 1, 3, 3, 3, 3, 1, 0])

In [230]:
class Generator(nn.Module):
    
    def __init__(self, input_length):
        super().__init__()
        self.fc = nn.Linear(int(input_length), int(input_length))
    
    def forward(self, x):
        return F.sigmoid(self.fc(x))
 

In [231]:
'''If we were building a GAN to do something more 
complicated on say images we would probably train 
it using random noise generated from a normal 
distribution and gradually upsample and reshape 
it until it’s the same size as the data we are trying to copy. '''

'If we were building a GAN to do something more \ncomplicated on say images we would probably train \nit using random noise generated from a normal \ndistribution and gradually upsample and reshape \nit until it’s the same size as the data we are trying to copy. '

In [232]:
# 2 dots, 4 noodles so to speak
net = Generator(2)

list(net.parameters())

[Parameter containing:
 tensor([[ 0.4901,  0.6977],
         [ 0.0996, -0.3970]], requires_grad=True), Parameter containing:
 tensor([ 0.3716, -0.2405], requires_grad=True)]

In [233]:
class Discriminator(nn.Module):
    
    def __init__(self, input_length):
        super().__init__()
        self.fc = nn.Linear(int(input_length), 1)
        
    def forward(self, x):
        return F.sigmoid(self.fc(x))
    
    
    

In [234]:
net = Discriminator(2)
list(net.parameters())
#expect 1 dot, 3 noodles

[Parameter containing:
 tensor([[-0.3078, -0.3047]], requires_grad=True), Parameter containing:
 tensor([-0.1248], requires_grad=True)]

In [ ]:
'''we pass two batches of data to our model 
at every training step. One batch is random 
noise which will cause the generator to create 
some generated data, and the second batch is
composed solely of 
data from our true distribution. '''

In [238]:
torch.randint(0, 2, size=(2, 5)).float().shape

torch.Size([2, 5])

In [250]:
def train(max_int = 128, batch_size = 16, training_steps = 500):
    
    input_length = int(math.log(max_int, 2))
    
    generator = Generator(input_length).to(device)
    discriminator = Discriminator(input_length).to(device)
    
    generator_optimizer = torch.optim.Adam(generator.parameters(), lr = 0.001)
    discriminator_optimizer = torch.optim.Adam(discriminator.parameters(), lr = 0.001)
    
    loss_function = nn.BCELoss()
    
    for i in range(training_steps):
        
        
       
        
        noise = torch.randint(0, 2, size =(batch_size, input_length)).float()
        
        #####################################################
        generator_optimizer.zero_grad()
        
        generated_data = generator(noise.to(device)) #
        
        true_labels, true_data = makeEvenData(max_int, batch_size = batch_size)
        true_labels = torch.tensor(true_labels).float().to(device)
        true_data = torch.tensor(true_data).float().to(device)
        
        
        
        generator_discriminator_out = discriminator(generated_data) #
        generator_loss = loss_function(generator_discriminator_out, true_labels)#note true_labels is nothing but torch.ones(batch_size)
        generator_loss.backward()
        generator_optimizer.step()
        
        ######################################################         
        discriminator_optimizer.zero_grad()
        
        true_discriminator_out = discriminator(true_data)
        true_discriminator_loss = loss_function(true_discriminator_out, true_labels)
        
        ######################################################
        #why did i detach it? and why can't i type this night AA A FUUUUUU
        
        
        #http://www.bnikolic.co.uk/blog/pytorch-detach.html
        
        
        generator_discriminator_out = discriminator(generated_data.detach().to(device))
        generator_discriminator_loss = loss_function(generator_discriminator_out, torch.zeros(batch_size).to(device))
        discriminator_loss = (true_discriminator_loss + generator_discriminator_loss) / 2
        discriminator_loss.backward()
        discriminator_optimizer.step()
        print(generator(torch.randint(0, 2, size =(16, 7)).float().to(device)))
    
        
        
        

In [251]:
#NOT WORKING RETRY LATER


tensor([[0.3458, 0.7332, 0.4655, 0.4336, 0.5688, 0.6612, 0.5024],
        [0.3750, 0.5240, 0.5315, 0.4146, 0.4754, 0.4363, 0.5476],
        [0.4376, 0.5909, 0.4598, 0.3998, 0.5524, 0.4404, 0.4000],
        [0.3477, 0.5607, 0.5641, 0.3758, 0.5599, 0.4423, 0.5772],
        [0.3574, 0.6372, 0.5663, 0.3893, 0.5884, 0.4381, 0.5108],
        [0.3700, 0.7397, 0.4992, 0.4348, 0.5678, 0.6035, 0.4255],
        [0.4190, 0.6412, 0.5343, 0.3552, 0.5857, 0.4282, 0.4343],
        [0.4561, 0.5083, 0.6721, 0.5762, 0.4709, 0.3892, 0.4321],
        [0.2583, 0.7298, 0.5162, 0.3773, 0.6262, 0.6232, 0.5284],
        [0.2705, 0.6699, 0.5476, 0.3650, 0.5976, 0.5676, 0.5180],
        [0.5440, 0.4943, 0.5523, 0.5226, 0.4626, 0.3742, 0.4324],
        [0.3428, 0.7671, 0.5320, 0.3953, 0.6485, 0.6094, 0.4552],
        [0.4318, 0.6335, 0.4821, 0.4450, 0.5305, 0.5411, 0.5618],
        [0.3696, 0.6649, 0.4547, 0.3174, 0.5887, 0.4901, 0.4412],
        [0.3848, 0.6810, 0.5306, 0.4219, 0.5381, 0.5471, 0.4153],
        [0

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.3340, 0.7741, 0.5222, 0.3859, 0.6394, 0.6000, 0.4650],
        [0.3511, 0.7348, 0.4478, 0.4318, 0.6076, 0.6119, 0.4301],
        [0.3719, 0.6928, 0.5170, 0.4086, 0.5245, 0.5336, 0.4287],
        [0.4753, 0.4939, 0.5803, 0.5551, 0.4616, 0.3800, 0.5127],
        [0.4484, 0.5161, 0.6652, 0.5686, 0.4632, 0.3818, 0.4397],
        [0.4656, 0.6411, 0.5002, 0.4464, 0.5713, 0.4283, 0.4108],
        [0.4076, 0.6519, 0.5226, 0.3446, 0.5742, 0.4168, 0.4459],
        [0.3697, 0.5787, 0.6222, 0.4859, 0.5508, 0.4481, 0.4767],
        [0.3203, 0.7516, 0.5020, 0.3307, 0.6078, 0.5380, 0.3916],
        [0.3935, 0.4954, 0.5711, 0.4492, 0.4674, 0.4302, 0.6216],
        [0.4981, 0.5611, 0.4833, 0.5306, 0.4896, 0.4874, 0.5238],
        [0.3444, 0.7346, 0.4123, 0.3187, 0.6063, 0.5360, 0.4632],
        [0.3260, 0.6645, 0.6452, 0.3950, 0.5824, 0.4323, 0.4456],
        [0.3283, 0.6350, 0.5270, 0.3826, 0.5835, 0.4939, 0.5931],
        [0.4109, 0.5748, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.4071, 0.5783, 0.6046, 0.5801, 0.4939, 0.4993, 0.5275],
        [0.4355, 0.6367, 0.4623, 0.4412, 0.5682, 0.4858, 0.4914],
        [0.3243, 0.6773, 0.3986, 0.2964, 0.5664, 0.5285, 0.5419],
        [0.3461, 0.6086, 0.4844, 0.4123, 0.4897, 0.4781, 0.5732],
        [0.4387, 0.5939, 0.3971, 0.4804, 0.4847, 0.5416, 0.5387],
        [0.3546, 0.6073, 0.5225, 0.5345, 0.4931, 0.5574, 0.5383],
        [0.3338, 0.7428, 0.4008, 0.3085, 0.5948, 0.5242, 0.4749],
        [0.3421, 0.7417, 0.4380, 0.4221, 0.5981, 0.6024, 0.4398],
        [0.2869, 0.7208, 0.5795, 0.4026, 0.6083, 0.5476, 0.5372],
        [0.3939, 0.7181, 0.5213, 0.4678, 0.5989, 0.5453, 0.4291],
        [0.3780, 0.6085, 0.4150, 0.3725, 0.4838, 0.5260, 0.5778],
        [0.4084, 0.6185, 0.4822, 0.4902, 0.4823, 0.5396, 0.4695],
        [0.2896, 0.6830, 0.5135, 0.4411, 0.5261, 0.6022, 0.5838],
        [0.4539, 0.5912, 0.5277, 0.4140, 0.4798, 0.4029, 0.4939],
        [0.4539, 0.5912, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.3773, 0.5593, 0.5697, 0.5051, 0.4445, 0.4208, 0.4682],
        [0.4568, 0.4209, 0.5703, 0.5330, 0.4250, 0.3766, 0.5868],
        [0.4599, 0.5897, 0.5101, 0.4126, 0.5201, 0.3530, 0.4216],
        [0.3044, 0.6203, 0.5234, 0.4228, 0.5323, 0.4887, 0.5052],
        [0.3058, 0.6804, 0.6234, 0.3730, 0.5593, 0.4095, 0.4688],
        [0.2975, 0.7353, 0.5991, 0.3909, 0.5943, 0.4721, 0.4733],
        [0.3940, 0.6800, 0.4002, 0.3846, 0.5530, 0.4686, 0.4387],
        [0.4005, 0.6843, 0.5745, 0.4289, 0.4996, 0.4498, 0.4431],
        [0.4675, 0.5000, 0.5726, 0.5473, 0.4537, 0.3726, 0.5206],
        [0.4533, 0.6103, 0.4184, 0.4700, 0.4720, 0.4680, 0.4730],
        [0.4005, 0.6843, 0.5745, 0.4289, 0.4996, 0.4498, 0.4431],
        [0.4157, 0.6775, 0.5668, 0.4368, 0.5495, 0.4073, 0.3637],
        [0.2938, 0.7692, 0.4706, 0.3038, 0.5774, 0.5067, 0.4218],
        [0.5001, 0.5011, 0.5010, 0.5038, 0.4459, 0.4166, 0.5272],
        [0.3732, 0.5704, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.3538, 0.5413, 0.4848, 0.3855, 0.4864, 0.3578, 0.5038],
        [0.2858, 0.6231, 0.4720, 0.2982, 0.5157, 0.3975, 0.5535],
        [0.2491, 0.7073, 0.5269, 0.3177, 0.5432, 0.4518, 0.4949],
        [0.4716, 0.4341, 0.5919, 0.5228, 0.4127, 0.3104, 0.5218],
        [0.3347, 0.7110, 0.4759, 0.3701, 0.4832, 0.4928, 0.4692],
        [0.3484, 0.5907, 0.6000, 0.4630, 0.5275, 0.4253, 0.4999],
        [0.3603, 0.6147, 0.3964, 0.3550, 0.4645, 0.5070, 0.5964],
        [0.2810, 0.6691, 0.5876, 0.3687, 0.5566, 0.4671, 0.5496],
        [0.3324, 0.6136, 0.4688, 0.3976, 0.4741, 0.4627, 0.5883],
        [0.3772, 0.5046, 0.5540, 0.4324, 0.4501, 0.4134, 0.6377],
        [0.3324, 0.6136, 0.4688, 0.3976, 0.4741, 0.4627, 0.5883],
        [0.3275, 0.7623, 0.4522, 0.3896, 0.5210, 0.5579, 0.4719],
        [0.3369, 0.5933, 0.5593, 0.3417, 0.5205, 0.3466, 0.5388],
        [0.3370, 0.5281, 0.4588, 0.3917, 0.4952, 0.4242, 0.5730],
        [0.3437, 0.6719, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.4199, 0.6542, 0.4769, 0.4087, 0.4906, 0.4408, 0.5234],
        [0.4381, 0.6046, 0.4032, 0.4549, 0.4564, 0.4528, 0.4884],
        [0.2903, 0.7329, 0.3459, 0.2873, 0.5715, 0.5616, 0.5764],
        [0.3645, 0.6608, 0.4764, 0.3050, 0.5285, 0.3732, 0.4914],
        [0.4029, 0.5045, 0.5644, 0.4268, 0.4837, 0.3032, 0.4964],
        [0.2738, 0.6629, 0.5785, 0.3603, 0.5474, 0.4581, 0.5586],
        [0.3455, 0.5343, 0.4753, 0.3769, 0.4770, 0.3494, 0.5130],
        [0.4381, 0.6046, 0.4032, 0.4549, 0.4564, 0.4528, 0.4884],
        [0.4217, 0.5932, 0.3803, 0.4632, 0.4670, 0.5243, 0.5560],
        [0.3809, 0.5600, 0.5186, 0.4571, 0.5338, 0.4312, 0.5649],
        [0.4217, 0.5932, 0.3803, 0.4632, 0.4670, 0.5243, 0.5560],
        [0.3512, 0.6597, 0.5946, 0.4697, 0.5486, 0.4137, 0.4408],
        [0.3819, 0.6117, 0.4027, 0.3463, 0.4943, 0.3846, 0.4566],
        [0.3940, 0.6701, 0.5439, 0.4150, 0.5266, 0.3857, 0.3850],
        [0.2762, 0.6214, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.3207, 0.5749, 0.5405, 0.3258, 0.5016, 0.3304, 0.5570],
        [0.4351, 0.5262, 0.4151, 0.4237, 0.4081, 0.3786, 0.4969],
        [0.3767, 0.5723, 0.5448, 0.4356, 0.4675, 0.3985, 0.5847],
        [0.3714, 0.5976, 0.3915, 0.3363, 0.4825, 0.3741, 0.4679],
        [0.3967, 0.5039, 0.6089, 0.5413, 0.4372, 0.4158, 0.5436],
        [0.2533, 0.6580, 0.4080, 0.3090, 0.5469, 0.5166, 0.6373],
        [0.2771, 0.6824, 0.5047, 0.4020, 0.4826, 0.4999, 0.5489],
        [0.4306, 0.5950, 0.3956, 0.4474, 0.4485, 0.4452, 0.4962],
        [0.3528, 0.6699, 0.3800, 0.3511, 0.4741, 0.4839, 0.5494],
        [0.4414, 0.4828, 0.5391, 0.5462, 0.4546, 0.4323, 0.5968],
        [0.4176, 0.5619, 0.4592, 0.3957, 0.5039, 0.3957, 0.5151],
        [0.2827, 0.7233, 0.3372, 0.2799, 0.5619, 0.5524, 0.5855],
        [0.3330, 0.5911, 0.4456, 0.3911, 0.5086, 0.4053, 0.5217],
        [0.4561, 0.4921, 0.5610, 0.5360, 0.4420, 0.3619, 0.5322],
        [0.4286, 0.6461, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.3613, 0.5811, 0.3806, 0.3270, 0.4710, 0.3640, 0.4788],
        [0.4108, 0.5776, 0.3692, 0.4522, 0.4553, 0.5131, 0.5672],
        [0.3915, 0.4952, 0.6034, 0.5361, 0.4316, 0.4106, 0.5490],
        [0.3379, 0.6405, 0.5796, 0.4554, 0.5333, 0.3996, 0.4555],
        [0.3329, 0.6513, 0.3524, 0.3540, 0.4790, 0.5500, 0.6204],
        [0.4081, 0.5649, 0.4796, 0.3702, 0.4321, 0.3590, 0.5409],
        [0.2217, 0.6673, 0.4871, 0.2861, 0.5034, 0.4145, 0.5334],
        [0.2110, 0.7234, 0.4488, 0.3181, 0.5609, 0.5594, 0.5938],
        [0.4906, 0.4874, 0.4978, 0.4697, 0.4089, 0.3257, 0.4858],
        [0.4424, 0.4082, 0.5554, 0.5187, 0.4103, 0.3631, 0.6010],
        [0.3418, 0.6968, 0.4352, 0.3086, 0.5484, 0.4198, 0.5112],
        [0.3178, 0.5016, 0.4364, 0.3715, 0.4724, 0.4031, 0.5943],
        [0.3443, 0.7066, 0.4904, 0.4232, 0.5114, 0.5511, 0.5490],
        [0.2720, 0.6570, 0.4670, 0.4128, 0.5374, 0.5226, 0.5396],
        [0.3731, 0.6414, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.4027, 0.6125, 0.4279, 0.4089, 0.5336, 0.4524, 0.5254],
        [0.2909, 0.6517, 0.4229, 0.3250, 0.4301, 0.4423, 0.5207],
        [0.3889, 0.5466, 0.4520, 0.3752, 0.4390, 0.4242, 0.6103],
        [0.3083, 0.6334, 0.5621, 0.4545, 0.4923, 0.5119, 0.6057],
        [0.2762, 0.5772, 0.4941, 0.3671, 0.4683, 0.3693, 0.4890],
        [0.4164, 0.5720, 0.3809, 0.4336, 0.4332, 0.4310, 0.5109],
        [0.3250, 0.6117, 0.4243, 0.2901, 0.5105, 0.4161, 0.5857],
        [0.3563, 0.5515, 0.5151, 0.4389, 0.4725, 0.4636, 0.6536],
        [0.3189, 0.5640, 0.5960, 0.4140, 0.4312, 0.3659, 0.5492],
        [0.2520, 0.5673, 0.4271, 0.2642, 0.4703, 0.3572, 0.5961],
        [0.3365, 0.6432, 0.3621, 0.3354, 0.4549, 0.4660, 0.5674],
        [0.3649, 0.6525, 0.4264, 0.4490, 0.4529, 0.4790, 0.4596],
        [0.3996, 0.5500, 0.4701, 0.3623, 0.4228, 0.3511, 0.5498],
        [0.4038, 0.5386, 0.4441, 0.3826, 0.4886, 0.3822, 0.5296],
        [0.3649, 0.6525, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.2866, 0.6943, 0.3731, 0.3620, 0.5317, 0.5394, 0.5048],
        [0.4771, 0.5414, 0.4681, 0.4854, 0.4399, 0.3806, 0.4941],
        [0.3195, 0.4949, 0.4967, 0.4676, 0.4067, 0.4453, 0.5828],
        [0.4356, 0.3962, 0.5480, 0.5122, 0.4031, 0.3569, 0.6077],
        [0.3973, 0.5260, 0.4369, 0.3766, 0.4812, 0.3760, 0.5365],
        [0.2206, 0.6882, 0.3663, 0.2487, 0.5050, 0.4993, 0.5690],
        [0.3061, 0.4768, 0.4219, 0.3595, 0.4576, 0.3903, 0.6077],
        [0.3424, 0.5446, 0.3598, 0.3099, 0.4487, 0.3454, 0.5000],
        [0.3787, 0.4141, 0.4676, 0.4383, 0.3721, 0.3270, 0.5723],
        [0.2617, 0.6855, 0.3123, 0.2599, 0.5336, 0.5263, 0.6114],
        [0.2468, 0.6102, 0.5416, 0.3298, 0.5099, 0.4238, 0.5934],
        [0.3672, 0.4586, 0.5182, 0.4152, 0.4719, 0.3479, 0.5847],
        [0.3977, 0.6034, 0.4224, 0.4042, 0.5279, 0.4473, 0.5307],
        [0.4069, 0.6037, 0.4384, 0.3895, 0.5096, 0.3713, 0.4703],
        [0.3142, 0.4771, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.4623, 0.4526, 0.4611, 0.4673, 0.4069, 0.3808, 0.5651],
        [0.2428, 0.5499, 0.4656, 0.3581, 0.4172, 0.4707, 0.6463],
        [0.4623, 0.4526, 0.4611, 0.4673, 0.4069, 0.3808, 0.5651],
        [0.3198, 0.5331, 0.3571, 0.2955, 0.3896, 0.3767, 0.5915],
        [0.3131, 0.6076, 0.5433, 0.4530, 0.5311, 0.4586, 0.5351],
        [0.2623, 0.6193, 0.4595, 0.3783, 0.4950, 0.4229, 0.5017],
        [0.3644, 0.5306, 0.4997, 0.4404, 0.5148, 0.4142, 0.5824],
        [0.3671, 0.4852, 0.4331, 0.4792, 0.4310, 0.4689, 0.6279],
        [0.3671, 0.4852, 0.4331, 0.4792, 0.4310, 0.4689, 0.6279],
        [0.3065, 0.6126, 0.5657, 0.4286, 0.4612, 0.4224, 0.5585],
        [0.2658, 0.6126, 0.3842, 0.3206, 0.4246, 0.4995, 0.6020],
        [0.2314, 0.5317, 0.3917, 0.2627, 0.4682, 0.4147, 0.6697],
        [0.2933, 0.5951, 0.4904, 0.3239, 0.5128, 0.3682, 0.5839],
        [0.3957, 0.5495, 0.3537, 0.4377, 0.4385, 0.4977, 0.5828],
        [0.3727, 0.4017, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.2732, 0.6653, 0.3561, 0.3481, 0.5132, 0.5233, 0.5220],
        [0.2442, 0.6108, 0.4582, 0.3639, 0.4362, 0.4579, 0.5917],
        [0.3665, 0.3886, 0.4532, 0.4266, 0.3587, 0.3160, 0.5854],
        [0.1893, 0.6687, 0.4122, 0.2912, 0.5236, 0.5262, 0.6270],
        [0.2462, 0.5754, 0.3060, 0.2252, 0.4646, 0.4334, 0.6362],
        [0.3971, 0.5335, 0.3606, 0.4156, 0.4118, 0.4122, 0.5313],
        [0.3010, 0.5998, 0.5585, 0.4229, 0.4540, 0.4163, 0.5651],
        [0.3673, 0.5178, 0.5089, 0.4197, 0.4893, 0.3348, 0.5293],
        [0.2796, 0.5032, 0.4812, 0.3069, 0.4768, 0.3667, 0.6530],
        [0.3225, 0.5953, 0.3186, 0.3380, 0.4987, 0.4797, 0.5679],
        [0.2373, 0.6585, 0.5120, 0.3447, 0.5416, 0.4839, 0.6011],
        [0.2732, 0.6653, 0.3561, 0.3481, 0.5132, 0.5233, 0.5220],
        [0.3282, 0.5896, 0.3301, 0.3220, 0.4771, 0.3994, 0.5110],
        [0.3113, 0.5129, 0.3471, 0.2882, 0.3792, 0.3678, 0.6013],
        [0.2732, 0.6653, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.3532, 0.4285, 0.5013, 0.4021, 0.4551, 0.3348, 0.5997],
        [0.2827, 0.5690, 0.4759, 0.3140, 0.4983, 0.3567, 0.5968],
        [0.3099, 0.5655, 0.4625, 0.3617, 0.4226, 0.4402, 0.5936],
        [0.3099, 0.5655, 0.4625, 0.3617, 0.4226, 0.4402, 0.5936],
        [0.2467, 0.6323, 0.2985, 0.2291, 0.4825, 0.4198, 0.5823],
        [0.3113, 0.5339, 0.4765, 0.4636, 0.4132, 0.4219, 0.5373],
        [0.3811, 0.4405, 0.3519, 0.3966, 0.3773, 0.4106, 0.6032],
        [0.2009, 0.6162, 0.3412, 0.2128, 0.4431, 0.3848, 0.5492],
        [0.3307, 0.6000, 0.3807, 0.4387, 0.4402, 0.5303, 0.5488],
        [0.3234, 0.5577, 0.4546, 0.3691, 0.4719, 0.3978, 0.5122],
        [0.2343, 0.5066, 0.4580, 0.3272, 0.3770, 0.3742, 0.6103],
        [0.3351, 0.5909, 0.3913, 0.4196, 0.4172, 0.4474, 0.4933],
        [0.2565, 0.6895, 0.4295, 0.2848, 0.5152, 0.4213, 0.5092],
        [0.2421, 0.5080, 0.4391, 0.3518, 0.4479, 0.4120, 0.5846],
        [0.2669, 0.6503, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.3611, 0.4680, 0.4251, 0.3293, 0.3793, 0.3162, 0.5908],
        [0.2346, 0.5231, 0.2954, 0.2002, 0.4184, 0.3364, 0.6039],
        [0.2751, 0.5686, 0.4593, 0.3275, 0.5165, 0.4318, 0.6534],
        [0.1909, 0.6030, 0.3200, 0.2196, 0.4540, 0.4555, 0.6143],
        [0.1798, 0.6386, 0.3947, 0.2800, 0.5057, 0.5111, 0.6421],
        [0.3781, 0.4149, 0.3537, 0.3717, 0.3474, 0.3265, 0.5570],
        [0.3037, 0.5661, 0.5364, 0.4201, 0.4897, 0.3637, 0.4959],
        [0.2878, 0.5863, 0.5348, 0.4326, 0.4650, 0.4882, 0.6295],
        [0.3850, 0.5066, 0.3473, 0.4049, 0.3981, 0.4005, 0.5444],
        [0.3114, 0.5694, 0.3062, 0.3282, 0.4844, 0.4676, 0.5808],
        [0.3348, 0.4265, 0.5036, 0.3905, 0.4010, 0.3703, 0.6800],
        [0.3144, 0.5569, 0.3143, 0.3102, 0.4593, 0.3851, 0.5273],
        [0.3195, 0.5286, 0.4551, 0.3440, 0.4382, 0.3138, 0.4662],
        [0.2714, 0.4310, 0.4005, 0.3309, 0.3802, 0.4074, 0.7062],
        [0.2878, 0.5863, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.1896, 0.6701, 0.3045, 0.2391, 0.4976, 0.5268, 0.6113],
        [0.2210, 0.4667, 0.4362, 0.3136, 0.3571, 0.3577, 0.6286],
        [0.3899, 0.5729, 0.4702, 0.4941, 0.4496, 0.4810, 0.5294],
        [0.3002, 0.4449, 0.3109, 0.2750, 0.3959, 0.3049, 0.5497],
        [0.2331, 0.5946, 0.2806, 0.2184, 0.4615, 0.4028, 0.6008],
        [0.3057, 0.6108, 0.4469, 0.3630, 0.4339, 0.4216, 0.5436],
        [0.2350, 0.5793, 0.4063, 0.2614, 0.4652, 0.4087, 0.5940],
        [0.2909, 0.6087, 0.3667, 0.2844, 0.5119, 0.4502, 0.6199],
        [0.3120, 0.4788, 0.3719, 0.3933, 0.3725, 0.4371, 0.5758],
        [0.2660, 0.4475, 0.4667, 0.2755, 0.4288, 0.2764, 0.6226],
        [0.3899, 0.5729, 0.4702, 0.4941, 0.4496, 0.4810, 0.5294],
        [0.3917, 0.5572, 0.4779, 0.4722, 0.4232, 0.3966, 0.4769],
        [0.3690, 0.5061, 0.5679, 0.5193, 0.4225, 0.3747, 0.5178],
        [0.3002, 0.4449, 0.3109, 0.2750, 0.3959, 0.3049, 0.5497],
        [0.3549, 0.4580, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.2196, 0.4777, 0.2749, 0.1897, 0.3950, 0.3191, 0.6247],
        [0.3762, 0.4458, 0.4742, 0.4306, 0.3617, 0.3157, 0.4991],
        [0.1843, 0.6531, 0.2958, 0.2342, 0.4875, 0.5188, 0.6198],
        [0.1711, 0.6084, 0.3779, 0.2706, 0.4886, 0.4971, 0.6561],
        [0.3405, 0.3998, 0.4848, 0.3912, 0.4393, 0.3233, 0.6135],
        [0.2991, 0.6138, 0.4325, 0.3793, 0.4538, 0.5015, 0.6009],
        [0.2598, 0.4507, 0.4520, 0.2896, 0.4485, 0.3452, 0.6760],
        [0.2798, 0.4339, 0.3085, 0.2634, 0.3400, 0.3356, 0.6379],
        [0.1783, 0.5399, 0.3036, 0.1936, 0.4024, 0.3530, 0.5863],
        [0.3636, 0.3836, 0.3373, 0.3604, 0.3316, 0.3141, 0.5727],
        [0.2269, 0.5761, 0.2723, 0.2139, 0.4515, 0.3952, 0.6095],
        [0.2991, 0.6138, 0.4325, 0.3793, 0.4538, 0.5015, 0.6009],
        [0.2254, 0.4590, 0.4124, 0.3348, 0.4220, 0.3912, 0.6076],
        [0.1652, 0.5110, 0.3809, 0.2420, 0.4311, 0.4149, 0.6705],
        [0.3471, 0.4357, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.2565, 0.3729, 0.3841, 0.2982, 0.3337, 0.3113, 0.6798],
        [0.2854, 0.4077, 0.2932, 0.2647, 0.3767, 0.2918, 0.5677],
        [0.2432, 0.5675, 0.3202, 0.3002, 0.4401, 0.4008, 0.5118],
        [0.2209, 0.5576, 0.2643, 0.2098, 0.4417, 0.3881, 0.6179],
        [0.3813, 0.5537, 0.4597, 0.4875, 0.4395, 0.4731, 0.5386],
        [0.2083, 0.4969, 0.4781, 0.2905, 0.4479, 0.3744, 0.6467],
        [0.2992, 0.4472, 0.3555, 0.3828, 0.3567, 0.4241, 0.5907],
        [0.2961, 0.5310, 0.2884, 0.3162, 0.4638, 0.4512, 0.5988],
        [0.2825, 0.5169, 0.2986, 0.2893, 0.3859, 0.4073, 0.6297],
        [0.2686, 0.3654, 0.3766, 0.3049, 0.3793, 0.2753, 0.6043],
        [0.2127, 0.4558, 0.2655, 0.1854, 0.3840, 0.3115, 0.6344],
        [0.2972, 0.4926, 0.4193, 0.3471, 0.4374, 0.3715, 0.5436],
        [0.2345, 0.4658, 0.3214, 0.2688, 0.3824, 0.3231, 0.5294],
        [0.3813, 0.5537, 0.4597, 0.4875, 0.4395, 0.4731, 0.5386],
        [0.2646, 0.5400, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.2613, 0.4188, 0.5163, 0.3587, 0.3561, 0.3079, 0.6191],
        [0.4403, 0.4632, 0.4262, 0.4555, 0.3995, 0.3492, 0.5321],
        [0.2150, 0.5389, 0.2565, 0.2061, 0.4320, 0.3814, 0.6261],
        [0.2613, 0.4188, 0.5163, 0.3587, 0.3561, 0.3079, 0.6191],
        [0.2804, 0.4142, 0.2827, 0.2800, 0.3973, 0.3642, 0.6226],
        [0.2613, 0.5304, 0.4386, 0.3163, 0.4962, 0.4165, 0.6696],
        [0.2785, 0.3899, 0.2849, 0.2603, 0.3675, 0.2860, 0.5764],
        [0.2595, 0.5052, 0.4413, 0.2951, 0.4647, 0.3329, 0.6256],
        [0.3307, 0.4927, 0.4825, 0.4158, 0.4406, 0.4373, 0.6794],
        [0.4294, 0.3853, 0.4233, 0.4410, 0.3714, 0.3527, 0.5982],
        [0.4235, 0.4471, 0.5187, 0.5306, 0.4346, 0.4156, 0.6145],
        [0.2037, 0.4113, 0.4061, 0.2979, 0.3304, 0.3374, 0.6532],
        [0.2613, 0.4188, 0.5163, 0.3587, 0.3561, 0.3079, 0.6191],
        [0.2755, 0.4770, 0.3665, 0.3578, 0.4617, 0.4277, 0.6385],
        [0.4294, 0.3853, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.2819, 0.4576, 0.4352, 0.4377, 0.3748, 0.3919, 0.5732],
        [0.3311, 0.4176, 0.3821, 0.3288, 0.3711, 0.3691, 0.6694],
        [0.4186, 0.4164, 0.5182, 0.5040, 0.4009, 0.3302, 0.5707],
        [0.3282, 0.4866, 0.4792, 0.4141, 0.4375, 0.4351, 0.6818],
        [0.3552, 0.4885, 0.3774, 0.3490, 0.4477, 0.3261, 0.5268],
        [0.2606, 0.4516, 0.3399, 0.2408, 0.4229, 0.3484, 0.6608],
        [0.2007, 0.4211, 0.3956, 0.3153, 0.3515, 0.4159, 0.7015],
        [0.3396, 0.3636, 0.5457, 0.4670, 0.3447, 0.2856, 0.5559],
        [0.2108, 0.5039, 0.3668, 0.2432, 0.4255, 0.3802, 0.6282],
        [0.3411, 0.4967, 0.3850, 0.3419, 0.3992, 0.3655, 0.6073],
        [0.2996, 0.5239, 0.3418, 0.4126, 0.4003, 0.4984, 0.5852],
        [0.2708, 0.4234, 0.4988, 0.3860, 0.4271, 0.3442, 0.5923],
        [0.1594, 0.5627, 0.3543, 0.2596, 0.4640, 0.4793, 0.6756],
        [0.1908, 0.4038, 0.3262, 0.2274, 0.3999, 0.3620, 0.7227],
        [0.2674, 0.5108, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.3547, 0.5077, 0.3717, 0.3704, 0.4757, 0.4069, 0.5774],
        [0.2784, 0.4634, 0.2722, 0.2852, 0.4106, 0.3509, 0.5714],
        [0.2628, 0.3821, 0.4920, 0.3583, 0.3876, 0.2637, 0.5532],
        [0.3263, 0.4061, 0.3761, 0.3260, 0.3652, 0.3652, 0.6744],
        [0.2764, 0.5343, 0.4056, 0.3413, 0.3942, 0.3930, 0.5796],
        [0.2075, 0.5340, 0.2424, 0.2172, 0.4473, 0.4578, 0.6825],
        [0.2537, 0.3642, 0.2759, 0.2469, 0.3064, 0.3118, 0.6689],
        [0.3377, 0.3979, 0.4020, 0.4322, 0.3681, 0.3570, 0.6114],
        [0.2637, 0.4240, 0.4023, 0.3053, 0.3347, 0.3131, 0.6008],
        [0.2534, 0.4366, 0.3648, 0.3226, 0.3709, 0.3757, 0.6788],
        [0.3276, 0.3243, 0.3989, 0.4177, 0.3408, 0.3604, 0.6734],
        [0.3363, 0.4850, 0.3791, 0.3391, 0.3933, 0.3618, 0.6125],
        [0.2517, 0.4068, 0.3324, 0.2193, 0.3821, 0.2665, 0.6254],
        [0.2449, 0.3601, 0.3618, 0.3098, 0.3435, 0.3791, 0.7347],
        [0.2546, 0.4198, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.1935, 0.4876, 0.3170, 0.2526, 0.4491, 0.4375, 0.7148],
        [0.2017, 0.5500, 0.4503, 0.3117, 0.4813, 0.4390, 0.6514],
        [0.4172, 0.3605, 0.4091, 0.4338, 0.3581, 0.3442, 0.6105],
        [0.2613, 0.4176, 0.3518, 0.3271, 0.4124, 0.3325, 0.6086],
        [0.1407, 0.3887, 0.3341, 0.2053, 0.3512, 0.3004, 0.6690],
        [0.2136, 0.4969, 0.3776, 0.3529, 0.4470, 0.4504, 0.6196],
        [0.2095, 0.5041, 0.2940, 0.2775, 0.3562, 0.4183, 0.6250],
        [0.2622, 0.4406, 0.3951, 0.3250, 0.3590, 0.3921, 0.6499],
        [0.1921, 0.4075, 0.2332, 0.1879, 0.3763, 0.3677, 0.7078],
        [0.2476, 0.4702, 0.4228, 0.2876, 0.4463, 0.3224, 0.6407],
        [0.1870, 0.4042, 0.4437, 0.2558, 0.3819, 0.2752, 0.6319],
        [0.1573, 0.5328, 0.2550, 0.1982, 0.4042, 0.3947, 0.6185],
        [0.2479, 0.3489, 0.2687, 0.2439, 0.2988, 0.3072, 0.6758],
        [0.1885, 0.3755, 0.2320, 0.1719, 0.3432, 0.2868, 0.6698],
        [0.3318, 0.4739, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.1468, 0.4345, 0.2446, 0.1864, 0.3660, 0.3927, 0.6878],
        [0.1868, 0.4238, 0.4379, 0.2745, 0.4091, 0.3507, 0.6778],
        [0.3053, 0.3575, 0.4635, 0.3697, 0.3642, 0.3451, 0.7093],
        [0.1432, 0.3991, 0.2423, 0.1702, 0.3321, 0.3084, 0.6497],
        [0.2433, 0.3013, 0.3403, 0.2888, 0.3436, 0.2559, 0.6366],
        [0.1904, 0.4767, 0.3118, 0.2508, 0.4432, 0.4343, 0.7190],
        [0.1909, 0.4173, 0.3382, 0.2148, 0.3633, 0.2834, 0.6106],
        [0.2865, 0.4899, 0.3252, 0.4044, 0.3827, 0.4872, 0.6009],
        [0.2574, 0.4069, 0.3462, 0.3250, 0.4066, 0.3296, 0.6136],
        [0.2046, 0.4879, 0.2866, 0.2747, 0.3482, 0.4136, 0.6322],
        [0.2028, 0.5326, 0.3441, 0.2449, 0.4276, 0.3612, 0.5870],
        [0.2574, 0.4275, 0.3879, 0.3224, 0.3523, 0.3882, 0.6557],
        [0.2529, 0.3565, 0.4766, 0.3524, 0.3734, 0.2570, 0.5663],
        [0.1954, 0.4530, 0.3411, 0.2340, 0.3985, 0.3645, 0.6507],
        [0.3053, 0.3575, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.1953, 0.4934, 0.2262, 0.2112, 0.4252, 0.4455, 0.6991],
        [0.4087, 0.3951, 0.5059, 0.4990, 0.3895, 0.3242, 0.5809],
        [0.1849, 0.3689, 0.3669, 0.3044, 0.3248, 0.3992, 0.7228],
        [0.3177, 0.3038, 0.3861, 0.4125, 0.3291, 0.3537, 0.6834],
        [0.3896, 0.2891, 0.4981, 0.4561, 0.3265, 0.2508, 0.6057],
        [0.2389, 0.2907, 0.3338, 0.2869, 0.3372, 0.2532, 0.6422],
        [0.3252, 0.4175, 0.4540, 0.3896, 0.4359, 0.3019, 0.5768],
        [0.3104, 0.2719, 0.3817, 0.3856, 0.2958, 0.2734, 0.6461],
        [0.2701, 0.4971, 0.4818, 0.4173, 0.4708, 0.4156, 0.5881],
        [0.3896, 0.2891, 0.4981, 0.4561, 0.3265, 0.2508, 0.6057],
        [0.2155, 0.5030, 0.2766, 0.3016, 0.4232, 0.4584, 0.6016],
        [0.2423, 0.4050, 0.3485, 0.3166, 0.3547, 0.3667, 0.6920],
        [0.1421, 0.4685, 0.3228, 0.2294, 0.3964, 0.3712, 0.6618],
        [0.1781, 0.3417, 0.2175, 0.1677, 0.3250, 0.2782, 0.6853],
        [0.2451, 0.3239, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.3121, 0.3363, 0.4463, 0.3745, 0.4025, 0.3034, 0.6444],
        [0.2307, 0.3228, 0.3403, 0.3026, 0.3229, 0.3678, 0.7500],
        [0.1866, 0.4238, 0.3255, 0.2304, 0.3822, 0.3572, 0.6639],
        [0.2502, 0.3375, 0.2469, 0.2647, 0.3547, 0.3403, 0.6592],
        [0.1443, 0.4787, 0.2322, 0.1919, 0.3752, 0.3806, 0.6430],
        [0.3434, 0.4317, 0.2967, 0.4009, 0.3766, 0.4519, 0.6374],
        [0.2600, 0.3956, 0.3665, 0.3254, 0.3849, 0.3417, 0.5905],
        [0.1916, 0.4812, 0.2212, 0.2100, 0.4182, 0.4425, 0.7042],
        [0.3246, 0.3680, 0.3850, 0.4260, 0.3521, 0.3488, 0.6257],
        [0.2389, 0.3956, 0.3432, 0.3153, 0.3495, 0.3645, 0.6961],
        [0.2689, 0.4733, 0.3694, 0.3386, 0.4135, 0.3384, 0.5240],
        [0.2459, 0.4358, 0.3487, 0.3404, 0.3868, 0.4553, 0.7294],
        [0.3954, 0.3181, 0.4998, 0.4833, 0.3589, 0.3263, 0.6471],
        [0.1734, 0.3267, 0.2107, 0.1663, 0.3164, 0.2748, 0.6925],
        [0.2512, 0.3719, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.2252, 0.3359, 0.2944, 0.2096, 0.3420, 0.2504, 0.6597],
        [0.3117, 0.2924, 0.3780, 0.4107, 0.3218, 0.3507, 0.6895],
        [0.1781, 0.3477, 0.3538, 0.3017, 0.3128, 0.3939, 0.7321],
        [0.1689, 0.3132, 0.2043, 0.1652, 0.3082, 0.2721, 0.6993],
        [0.3426, 0.4646, 0.5282, 0.5264, 0.4181, 0.4389, 0.5968],
        [0.1630, 0.2938, 0.2818, 0.1976, 0.3211, 0.2618, 0.7216],
        [0.3330, 0.4216, 0.5207, 0.4977, 0.3784, 0.3488, 0.5582],
        [0.3310, 0.4031, 0.3882, 0.4534, 0.3869, 0.4374, 0.6650],
        [0.1896, 0.5099, 0.4269, 0.3058, 0.4581, 0.4285, 0.6692],
        [0.3830, 0.2779, 0.4894, 0.4542, 0.3193, 0.2484, 0.6125],
        [0.1895, 0.4893, 0.3210, 0.2400, 0.4029, 0.3513, 0.6078],
        [0.2079, 0.4801, 0.2655, 0.2990, 0.4098, 0.4530, 0.6127],
        [0.1763, 0.3696, 0.3117, 0.2096, 0.3366, 0.2734, 0.6342],
        [0.2179, 0.3157, 0.3894, 0.2480, 0.3556, 0.2406, 0.6836],
        [0.2444, 0.3933, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.3062, 0.3249, 0.4378, 0.3732, 0.3946, 0.3011, 0.6509],
        [0.2317, 0.3413, 0.3532, 0.2924, 0.2911, 0.2936, 0.6422],
        [0.2358, 0.3154, 0.4479, 0.3465, 0.3478, 0.2489, 0.5896],
        [0.2988, 0.2514, 0.3658, 0.3826, 0.2824, 0.2688, 0.6589],
        [0.2244, 0.3081, 0.3304, 0.3011, 0.3136, 0.3646, 0.7568],
        [0.1947, 0.4784, 0.2669, 0.2919, 0.3573, 0.4948, 0.6916],
        [0.3374, 0.4194, 0.2900, 0.3997, 0.3692, 0.4494, 0.6436],
        [0.2380, 0.2785, 0.3838, 0.3825, 0.2764, 0.2925, 0.6343],
        [0.1732, 0.3793, 0.4097, 0.2694, 0.3823, 0.3408, 0.6983],
        [0.2418, 0.3188, 0.2368, 0.2631, 0.3424, 0.3364, 0.6695],
        [0.2309, 0.3263, 0.2430, 0.2572, 0.2997, 0.3766, 0.7373],
        [0.2403, 0.3836, 0.3615, 0.3169, 0.3276, 0.3780, 0.6766],
        [0.1778, 0.4151, 0.2060, 0.1901, 0.3648, 0.3479, 0.6811],
        [0.2719, 0.4537, 0.3061, 0.3996, 0.3623, 0.4786, 0.6187],
        [0.3407, 0.4606, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.1675, 0.3309, 0.1988, 0.1810, 0.3307, 0.3498, 0.7419],
        [0.2403, 0.3644, 0.3212, 0.3204, 0.3803, 0.3211, 0.6356],
        [0.3272, 0.3956, 0.3832, 0.4531, 0.3821, 0.4362, 0.6689],
        [0.1694, 0.3860, 0.2798, 0.2260, 0.3740, 0.3353, 0.7077],
        [0.2584, 0.3997, 0.2930, 0.3721, 0.3182, 0.3845, 0.5873],
        [0.1676, 0.3444, 0.2957, 0.2087, 0.3205, 0.2700, 0.6487],
        [0.3186, 0.4658, 0.3514, 0.3560, 0.3980, 0.4373, 0.6774],
        [0.1769, 0.4470, 0.4066, 0.2812, 0.4049, 0.3367, 0.6435],
        [0.2215, 0.3148, 0.4499, 0.3395, 0.2994, 0.2821, 0.6704],
        [0.2436, 0.3104, 0.3874, 0.4099, 0.3077, 0.3759, 0.6729],
        [0.1224, 0.3180, 0.2037, 0.1644, 0.2858, 0.2923, 0.6908],
        [0.1749, 0.3886, 0.3044, 0.2284, 0.3601, 0.3512, 0.6818],
        [0.3843, 0.2836, 0.3748, 0.4001, 0.2975, 0.2565, 0.5956],
        [0.2295, 0.3723, 0.3286, 0.3137, 0.3353, 0.3605, 0.7073],
        [0.1647, 0.2897, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.2093, 0.2569, 0.3114, 0.2777, 0.2682, 0.2806, 0.7358],
        [0.3095, 0.2929, 0.2718, 0.3588, 0.2960, 0.3603, 0.6776],
        [0.1599, 0.3189, 0.3866, 0.2476, 0.3298, 0.2598, 0.6762],
        [0.2575, 0.4665, 0.4615, 0.4151, 0.4511, 0.4104, 0.6044],
        [0.2366, 0.4129, 0.3345, 0.3395, 0.3723, 0.4518, 0.7395],
        [0.2771, 0.2817, 0.4274, 0.3400, 0.3027, 0.2589, 0.6962],
        [0.1653, 0.2957, 0.2374, 0.2361, 0.2463, 0.3153, 0.6966],
        [0.3317, 0.4089, 0.2836, 0.3999, 0.3621, 0.4484, 0.6497],
        [0.1745, 0.4255, 0.2842, 0.2472, 0.4114, 0.4244, 0.7406],
        [0.2306, 0.2646, 0.3717, 0.3828, 0.2667, 0.2913, 0.6442],
        [0.2230, 0.3226, 0.3393, 0.2928, 0.2791, 0.2921, 0.6539],
        [0.1715, 0.3793, 0.2982, 0.2289, 0.3535, 0.3508, 0.6871],
        [0.1161, 0.2922, 0.2764, 0.1972, 0.2935, 0.2815, 0.7173],
        [0.1738, 0.2888, 0.2313, 0.2416, 0.2844, 0.2788, 0.6237],
        [0.2236, 0.3109, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.1578, 0.3012, 0.2677, 0.2171, 0.3360, 0.3384, 0.7674],
        [0.2282, 0.3753, 0.2318, 0.2702, 0.3097, 0.3722, 0.6952],
        [0.1616, 0.2874, 0.2315, 0.2375, 0.2405, 0.3158, 0.7023],
        [0.1674, 0.3862, 0.1918, 0.1914, 0.3448, 0.3466, 0.6972],
        [0.1853, 0.4534, 0.2525, 0.2934, 0.3408, 0.4936, 0.7047],
        [0.3265, 0.4482, 0.3373, 0.3640, 0.4388, 0.3947, 0.6083],
        [0.1786, 0.3234, 0.2346, 0.2646, 0.3168, 0.3618, 0.6623],
        [0.2183, 0.3438, 0.2797, 0.2299, 0.3573, 0.3251, 0.7120],
        [0.1532, 0.2726, 0.1821, 0.1660, 0.2796, 0.2688, 0.7238],
        [0.2368, 0.4680, 0.2928, 0.2621, 0.4299, 0.4101, 0.6848],
        [0.2423, 0.3133, 0.2804, 0.3600, 0.2833, 0.3878, 0.6601],
        [0.2455, 0.4006, 0.3239, 0.3471, 0.4158, 0.4091, 0.6747],
        [0.2083, 0.2996, 0.2696, 0.2103, 0.3160, 0.2476, 0.6823],
        [0.1683, 0.3713, 0.2924, 0.2301, 0.3474, 0.3512, 0.6921],
        [0.3237, 0.3895, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.1822, 0.3887, 0.2322, 0.2786, 0.3375, 0.3597, 0.6049],
        [0.2458, 0.4812, 0.3549, 0.3590, 0.3769, 0.4670, 0.6651],
        [0.2833, 0.2668, 0.4104, 0.3495, 0.3379, 0.2275, 0.6303],
        [0.2230, 0.4119, 0.2779, 0.2423, 0.3801, 0.3230, 0.6578],
        [0.2435, 0.3971, 0.3211, 0.3483, 0.4127, 0.4097, 0.6770],
        [0.2474, 0.3788, 0.2786, 0.3761, 0.3036, 0.3855, 0.6017],
        [0.3992, 0.3841, 0.3776, 0.4453, 0.3534, 0.3330, 0.5748],
        [0.3060, 0.3803, 0.4270, 0.3895, 0.4100, 0.2981, 0.5989],
        [0.3992, 0.3841, 0.3776, 0.4453, 0.3534, 0.3330, 0.5748],
        [0.2435, 0.3971, 0.3211, 0.3483, 0.4127, 0.4097, 0.6770],
        [0.3060, 0.3803, 0.4270, 0.3895, 0.4100, 0.2981, 0.5989],
        [0.1703, 0.4151, 0.2770, 0.2493, 0.4029, 0.4255, 0.7464],
        [0.3733, 0.2700, 0.3618, 0.4034, 0.2864, 0.2571, 0.6069],
        [0.2152, 0.3384, 0.2754, 0.2315, 0.3525, 0.3261, 0.7157],
        [0.2964, 0.3094, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.1625, 0.3591, 0.2821, 0.2346, 0.3364, 0.3543, 0.7011],
        [0.1665, 0.4210, 0.3852, 0.2870, 0.3843, 0.3391, 0.6605],
        [0.1272, 0.4384, 0.2846, 0.2521, 0.3869, 0.4562, 0.7320],
        [0.2535, 0.4118, 0.3873, 0.4573, 0.3617, 0.4668, 0.6561],
        [0.2852, 0.3256, 0.3231, 0.3220, 0.3144, 0.3521, 0.7159],
        [0.2231, 0.3504, 0.3350, 0.3231, 0.3034, 0.3796, 0.6977],
        [0.1759, 0.4733, 0.3994, 0.3100, 0.4309, 0.4284, 0.6897],
        [0.1800, 0.4422, 0.2446, 0.2980, 0.3315, 0.4966, 0.7122],
        [0.1102, 0.2825, 0.1814, 0.1709, 0.2583, 0.2960, 0.7161],
        [0.3175, 0.3948, 0.4989, 0.5015, 0.3591, 0.3487, 0.5761],
        [0.2391, 0.4039, 0.4372, 0.3925, 0.3948, 0.3244, 0.5801],
        [0.1703, 0.3908, 0.2338, 0.2755, 0.2902, 0.4031, 0.6841],
        [0.1703, 0.3908, 0.2338, 0.2755, 0.2902, 0.4031, 0.6841],
        [0.1468, 0.2606, 0.1735, 0.1702, 0.2683, 0.2719, 0.7337],
        [0.2828, 0.2306, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.2541, 0.4219, 0.2833, 0.4082, 0.3381, 0.4821, 0.6404],
        [0.2516, 0.4096, 0.3846, 0.4596, 0.3592, 0.4683, 0.6584],
        [0.2285, 0.3285, 0.4303, 0.3812, 0.3634, 0.3293, 0.6470],
        [0.2521, 0.4661, 0.3401, 0.3712, 0.4164, 0.4272, 0.5957],
        [0.2182, 0.2481, 0.3522, 0.3929, 0.2512, 0.2960, 0.6604],
        [0.3219, 0.3958, 0.2733, 0.4063, 0.3505, 0.4520, 0.6597],
        [0.3084, 0.3319, 0.3807, 0.4369, 0.3097, 0.3660, 0.6242],
        [0.2216, 0.2857, 0.2132, 0.2717, 0.3134, 0.3402, 0.6945],
        [0.1666, 0.4084, 0.2708, 0.2535, 0.3957, 0.4289, 0.7513],
        [0.1146, 0.3228, 0.1863, 0.1903, 0.2917, 0.3839, 0.7468],
        [0.3190, 0.3838, 0.3728, 0.4576, 0.3719, 0.4384, 0.6772],
        [0.2304, 0.2903, 0.3668, 0.4186, 0.2901, 0.3800, 0.6890],
        [0.2367, 0.4010, 0.4334, 0.3954, 0.3913, 0.3262, 0.5833],
        [0.2282, 0.4211, 0.3335, 0.3397, 0.3250, 0.3787, 0.6418],
        [0.2073, 0.3197, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.2925, 0.2675, 0.3529, 0.4193, 0.2995, 0.3538, 0.7087],
        [0.2159, 0.3341, 0.4350, 0.3775, 0.3164, 0.3716, 0.7198],
        [0.2382, 0.3683, 0.2672, 0.3869, 0.2920, 0.3929, 0.6136],
        [0.3041, 0.3440, 0.2582, 0.3842, 0.3042, 0.3639, 0.6328],
        [0.1650, 0.3837, 0.2260, 0.2835, 0.2815, 0.4100, 0.6923],
        [0.1951, 0.2827, 0.2513, 0.2215, 0.2966, 0.2556, 0.6997],
        [0.2344, 0.3992, 0.4299, 0.3989, 0.3880, 0.3285, 0.5863],
        [0.1827, 0.4163, 0.3239, 0.3572, 0.3907, 0.4444, 0.6655],
        [0.2137, 0.2811, 0.4105, 0.3605, 0.3154, 0.2545, 0.6204],
        [0.2344, 0.3992, 0.4299, 0.3989, 0.3880, 0.3285, 0.5863],
        [0.2773, 0.2696, 0.2954, 0.3121, 0.3074, 0.2423, 0.6218],
        [0.2779, 0.3109, 0.4237, 0.3747, 0.3292, 0.3433, 0.7360],
        [0.2128, 0.3896, 0.3657, 0.2914, 0.3897, 0.3171, 0.6854],
        [0.3638, 0.2631, 0.3511, 0.4124, 0.2775, 0.2619, 0.6164],
        [0.1044, 0.2652, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.2013, 0.2869, 0.4146, 0.3583, 0.2717, 0.2926, 0.6965],
        [0.2343, 0.3564, 0.3634, 0.4408, 0.3097, 0.3823, 0.6340],
        [0.1912, 0.2722, 0.3437, 0.2630, 0.3136, 0.2478, 0.7182],
        [0.1543, 0.2608, 0.2032, 0.2630, 0.2532, 0.2939, 0.6564],
        [0.2045, 0.3278, 0.2610, 0.2436, 0.3366, 0.3366, 0.7284],
        [0.2377, 0.4017, 0.2216, 0.3125, 0.3789, 0.4316, 0.6693],
        [0.3017, 0.3191, 0.4877, 0.4947, 0.3257, 0.3574, 0.6464],
        [0.1642, 0.4174, 0.1852, 0.2225, 0.3662, 0.4499, 0.7420],
        [0.2139, 0.3334, 0.4318, 0.3813, 0.3138, 0.3747, 0.7220],
        [0.3012, 0.4336, 0.4415, 0.4156, 0.4016, 0.4300, 0.7086],
        [0.3001, 0.3327, 0.3534, 0.4370, 0.3229, 0.3529, 0.6522],
        [0.2872, 0.2833, 0.3580, 0.4203, 0.2629, 0.2898, 0.6003],
        [0.2483, 0.4077, 0.3799, 0.4653, 0.3548, 0.4727, 0.6622],
        [0.2775, 0.3207, 0.3138, 0.3316, 0.3057, 0.3596, 0.7233],
        [0.2142, 0.2545, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.2735, 0.2355, 0.2375, 0.3570, 0.2357, 0.2929, 0.6714],
        [0.1129, 0.3911, 0.1781, 0.2140, 0.3029, 0.3971, 0.7050],
        [0.1537, 0.3021, 0.3073, 0.3238, 0.2712, 0.4081, 0.7653],
        [0.2714, 0.2692, 0.2889, 0.3219, 0.3011, 0.2490, 0.6283],
        [0.2121, 0.3337, 0.4290, 0.3858, 0.3115, 0.3783, 0.7240],
        [0.2114, 0.3586, 0.2127, 0.2905, 0.2873, 0.3893, 0.7150],
        [0.2310, 0.4105, 0.3155, 0.3610, 0.3587, 0.3496, 0.5745],
        [0.2714, 0.2692, 0.2889, 0.3219, 0.3011, 0.2490, 0.6283],
        [0.3160, 0.3942, 0.2676, 0.4156, 0.3442, 0.4596, 0.6654],
        [0.2224, 0.4419, 0.3771, 0.3188, 0.4340, 0.4082, 0.7153],
        [0.1007, 0.2647, 0.2409, 0.2213, 0.2580, 0.3024, 0.7482],
        [0.3874, 0.3774, 0.3650, 0.4593, 0.3416, 0.3422, 0.5864],
        [0.1081, 0.3090, 0.2546, 0.2379, 0.2995, 0.3848, 0.7703],
        [0.2039, 0.2901, 0.2107, 0.2783, 0.2637, 0.3926, 0.7665],
        [0.1685, 0.3756, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.3554, 0.2545, 0.4550, 0.4741, 0.2918, 0.2577, 0.6397],
        [0.1404, 0.2961, 0.3459, 0.2781, 0.2940, 0.2822, 0.7080],
        [0.1870, 0.2742, 0.3374, 0.2730, 0.3079, 0.2557, 0.7231],
        [0.1599, 0.2970, 0.2975, 0.3367, 0.3089, 0.3719, 0.7044],
        [0.2212, 0.4555, 0.2729, 0.2822, 0.4066, 0.4287, 0.7029],
        [0.1692, 0.4255, 0.3235, 0.3633, 0.3377, 0.4999, 0.7395],
        [0.1439, 0.2886, 0.2446, 0.2392, 0.3104, 0.3598, 0.7856],
        [0.2852, 0.3155, 0.3020, 0.3478, 0.3439, 0.3278, 0.6583],
        [0.2945, 0.3868, 0.3044, 0.3617, 0.3710, 0.3249, 0.5956],
        [0.1341, 0.2559, 0.1578, 0.1923, 0.2474, 0.2958, 0.7526],
        [0.1565, 0.4167, 0.3662, 0.3089, 0.3661, 0.3578, 0.6760],
        [0.1678, 0.4822, 0.2804, 0.2874, 0.3907, 0.4620, 0.6871],
        [0.1195, 0.4463, 0.1867, 0.2362, 0.3447, 0.4944, 0.7323],
        [0.2180, 0.4083, 0.4293, 0.4054, 0.3351, 0.3794, 0.6693],
        [0.2966, 0.3453, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.1849, 0.2878, 0.2388, 0.2438, 0.2832, 0.2757, 0.7120],
        [0.1547, 0.4331, 0.2624, 0.2773, 0.3390, 0.3817, 0.6639],
        [0.2438, 0.4114, 0.3741, 0.4781, 0.3495, 0.4834, 0.6670],
        [0.3532, 0.2664, 0.3406, 0.4334, 0.2688, 0.2757, 0.6261],
        [0.2060, 0.2603, 0.2392, 0.3788, 0.2193, 0.3340, 0.6605],
        [0.1179, 0.4506, 0.1845, 0.2431, 0.3416, 0.5024, 0.7348],
        [0.2088, 0.3376, 0.4241, 0.3968, 0.3075, 0.3874, 0.7275],
        [0.1479, 0.3604, 0.2445, 0.2564, 0.3336, 0.3629, 0.7390],
        [0.1661, 0.4857, 0.2780, 0.2938, 0.3880, 0.4685, 0.6893],
        [0.2549, 0.2696, 0.3964, 0.3701, 0.2778, 0.2780, 0.7187],
        [0.1981, 0.3331, 0.2535, 0.2590, 0.3281, 0.3521, 0.7352],
        [0.2804, 0.3847, 0.4182, 0.4038, 0.3485, 0.3518, 0.6869],
        [0.1761, 0.4334, 0.2221, 0.3345, 0.3556, 0.4806, 0.6597],
        [0.1398, 0.2636, 0.2855, 0.3189, 0.2272, 0.3365, 0.7480],
        [0.1957, 0.2466, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.1036, 0.3326, 0.1692, 0.2262, 0.2691, 0.4270, 0.7657],
        [0.2261, 0.3783, 0.2541, 0.4211, 0.2788, 0.4212, 0.6278],
        [0.2051, 0.3687, 0.2067, 0.3104, 0.2803, 0.4083, 0.7215],
        [0.2820, 0.3093, 0.4058, 0.4019, 0.3649, 0.3196, 0.6759],
        [0.1969, 0.3252, 0.3507, 0.3017, 0.3504, 0.3402, 0.7491],
        [0.2261, 0.3783, 0.2541, 0.4211, 0.2788, 0.4212, 0.6278],
        [0.1082, 0.3922, 0.2487, 0.2707, 0.3159, 0.4042, 0.7270],
        [0.1933, 0.2963, 0.4023, 0.3858, 0.2623, 0.3131, 0.7058],
        [0.2302, 0.4105, 0.2147, 0.3335, 0.3696, 0.4514, 0.6773],
        [0.2532, 0.2730, 0.3943, 0.3767, 0.2762, 0.2826, 0.7202],
        [0.4027, 0.4339, 0.3788, 0.4922, 0.3861, 0.4367, 0.6185],
        [0.1651, 0.4768, 0.3799, 0.3396, 0.4118, 0.4554, 0.7047],
        [0.3118, 0.3870, 0.3649, 0.4735, 0.3643, 0.4514, 0.6836],
        [0.2205, 0.4045, 0.3125, 0.3665, 0.3498, 0.4745, 0.7558],
        [0.1969, 0.3252, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.2504, 0.2901, 0.2865, 0.3444, 0.2534, 0.3061, 0.7089],
        [0.2689, 0.3197, 0.4127, 0.3995, 0.3199, 0.3630, 0.7435],
        [0.2148, 0.3535, 0.3033, 0.3781, 0.3225, 0.3786, 0.6478],
        [0.2297, 0.4011, 0.3041, 0.3794, 0.3941, 0.4361, 0.6921],
        [0.1809, 0.3000, 0.2345, 0.2603, 0.2787, 0.2904, 0.7163],
        [0.1963, 0.3047, 0.2035, 0.3052, 0.2556, 0.4189, 0.7735],
        [0.1367, 0.2751, 0.2808, 0.3380, 0.2234, 0.3528, 0.7518],
        [0.2059, 0.3464, 0.4203, 0.4107, 0.3043, 0.3989, 0.7302],
        [0.1397, 0.3016, 0.2389, 0.2585, 0.3041, 0.3799, 0.7902],
        [0.1553, 0.3104, 0.2909, 0.3606, 0.3025, 0.3926, 0.7103],
        [0.2132, 0.3680, 0.1998, 0.3256, 0.3194, 0.3744, 0.6538],
        [0.1293, 0.2608, 0.2241, 0.2460, 0.2604, 0.3028, 0.7709],
        [0.1916, 0.3022, 0.4001, 0.3948, 0.2607, 0.3199, 0.7074],
        [0.2961, 0.4409, 0.4358, 0.4304, 0.3962, 0.4426, 0.7127],
        [0.1432, 0.2813, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.1948, 0.3122, 0.2023, 0.3140, 0.2543, 0.4274, 0.7746],
        [0.2486, 0.2975, 0.2849, 0.3538, 0.2520, 0.3135, 0.7103],
        [0.2287, 0.4062, 0.3032, 0.3853, 0.3931, 0.4412, 0.6930],
        [0.1141, 0.4760, 0.1798, 0.2689, 0.3347, 0.5310, 0.7404],
        [0.1376, 0.3242, 0.1620, 0.2361, 0.2794, 0.4110, 0.7811],
        [0.2046, 0.3529, 0.4188, 0.4187, 0.3031, 0.4056, 0.7312],
        [0.1414, 0.2916, 0.1883, 0.3208, 0.2365, 0.3445, 0.6753],
        [0.2910, 0.3493, 0.3618, 0.4845, 0.2935, 0.4032, 0.6408],
        [0.1332, 0.3371, 0.2383, 0.2810, 0.2624, 0.3336, 0.7042],
        [0.1507, 0.4414, 0.3570, 0.3409, 0.3574, 0.3864, 0.6836],
        [0.3199, 0.4721, 0.3842, 0.5142, 0.3673, 0.4831, 0.6040],
        [0.1354, 0.2836, 0.2790, 0.3490, 0.2219, 0.3622, 0.7534],
        [0.1981, 0.3182, 0.2840, 0.3746, 0.2755, 0.3106, 0.6238],
        [0.4026, 0.4233, 0.4941, 0.5406, 0.4115, 0.4201, 0.6341],
        [0.2185, 0.4136, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.1619, 0.4982, 0.3757, 0.3621, 0.4075, 0.4763, 0.7081],
        [0.1792, 0.2819, 0.1879, 0.3130, 0.2141, 0.3579, 0.7559],
        [0.3209, 0.4590, 0.5009, 0.5587, 0.3932, 0.4632, 0.6189],
        [0.2108, 0.4362, 0.4204, 0.4425, 0.3274, 0.4099, 0.6765],
        [0.2115, 0.3715, 0.3004, 0.3989, 0.3195, 0.3961, 0.6507],
        [0.1140, 0.4690, 0.2600, 0.3112, 0.3588, 0.5167, 0.7529],
        [0.2647, 0.3471, 0.3016, 0.3755, 0.2941, 0.3974, 0.7335],
        [0.3670, 0.3261, 0.3541, 0.4774, 0.3083, 0.3707, 0.6570],
        [0.2004, 0.3937, 0.2032, 0.3372, 0.2760, 0.4336, 0.7256],
        [0.2003, 0.4182, 0.3492, 0.3364, 0.3734, 0.3561, 0.6990],
        [0.3187, 0.4785, 0.3834, 0.5211, 0.3664, 0.4890, 0.6048],
        [0.2020, 0.3751, 0.2916, 0.3719, 0.2992, 0.4085, 0.7372],
        [0.1130, 0.4886, 0.1788, 0.2796, 0.3331, 0.5424, 0.7417],
        [0.3798, 0.3805, 0.4723, 0.5306, 0.3596, 0.3442, 0.6085],
        [0.1548, 0.4352, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.1518, 0.3370, 0.2874, 0.3919, 0.2987, 0.4200, 0.7137],
        [0.1431, 0.3856, 0.3523, 0.3477, 0.3286, 0.4081, 0.7405],
        [0.2140, 0.3210, 0.3465, 0.4838, 0.2730, 0.4327, 0.7056],
        [0.2586, 0.2720, 0.2264, 0.4206, 0.2249, 0.3416, 0.6840],
        [0.2168, 0.4263, 0.3092, 0.3901, 0.3463, 0.4960, 0.7584],
        [0.2098, 0.4451, 0.4196, 0.4519, 0.3266, 0.4178, 0.6772],
        [0.2881, 0.3651, 0.3600, 0.5030, 0.2917, 0.4185, 0.6427],
        [0.2140, 0.3210, 0.3465, 0.4838, 0.2730, 0.4327, 0.7056],
        [0.1485, 0.4401, 0.2071, 0.3650, 0.2601, 0.4875, 0.7133],
        [0.1940, 0.3118, 0.2887, 0.3664, 0.2745, 0.4193, 0.7863],
        [0.2635, 0.3552, 0.3010, 0.3844, 0.2933, 0.4052, 0.7342],
        [0.3086, 0.4013, 0.3626, 0.4905, 0.3619, 0.4658, 0.6858],
        [0.1245, 0.3080, 0.1491, 0.2491, 0.2351, 0.3572, 0.7641],
        [0.3038, 0.4669, 0.3146, 0.4170, 0.4138, 0.4385, 0.6302],
        [0.1430, 0.3639, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.3458, 0.2816, 0.4473, 0.5176, 0.2854, 0.2864, 0.6464],
        [0.2466, 0.3050, 0.3890, 0.4186, 0.2715, 0.3136, 0.7246],
        [0.1914, 0.3602, 0.3457, 0.3399, 0.3450, 0.3743, 0.7532],
        [0.2598, 0.2622, 0.3207, 0.4654, 0.2450, 0.3243, 0.6969],
        [0.2856, 0.4087, 0.4044, 0.4493, 0.3882, 0.3417, 0.6187],
        [0.2091, 0.3929, 0.2992, 0.4223, 0.3177, 0.4161, 0.6524],
        [0.1984, 0.4362, 0.3481, 0.3539, 0.3719, 0.3715, 0.7002],
        [0.2933, 0.4577, 0.4339, 0.4483, 0.3942, 0.4579, 0.7143],
        [0.3196, 0.4682, 0.5003, 0.5682, 0.3924, 0.4714, 0.6196],
        [0.1952, 0.3138, 0.2309, 0.4535, 0.2112, 0.3942, 0.6705],
        [0.2466, 0.3050, 0.3890, 0.4186, 0.2715, 0.3136, 0.7246],
        [0.1358, 0.3378, 0.2356, 0.2947, 0.2996, 0.4170, 0.7934],
        [0.1478, 0.4747, 0.3544, 0.3732, 0.3541, 0.4154, 0.6865],
        [0.2907, 0.4819, 0.3217, 0.4159, 0.3670, 0.4879, 0.7024],
        [0.1681, 0.4881, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.2232, 0.4592, 0.2111, 0.3839, 0.3636, 0.4980, 0.6825],
        [0.2871, 0.3731, 0.3425, 0.4959, 0.3123, 0.3997, 0.6625],
        [0.2589, 0.2698, 0.3208, 0.4757, 0.2447, 0.3320, 0.6972],
        [0.2156, 0.4831, 0.3016, 0.4502, 0.3432, 0.4239, 0.5899],
        [0.3160, 0.4999, 0.3826, 0.5435, 0.3650, 0.5082, 0.6061],
        [0.1856, 0.3500, 0.3956, 0.4519, 0.2563, 0.3646, 0.7118],
        [0.2730, 0.4237, 0.4126, 0.4487, 0.3428, 0.3880, 0.6919],
        [0.1597, 0.5265, 0.3747, 0.3899, 0.4055, 0.5016, 0.7095],
        [0.2842, 0.3984, 0.2438, 0.4657, 0.2880, 0.4311, 0.6495],
        [0.3022, 0.4813, 0.3144, 0.4318, 0.4130, 0.4513, 0.6308],
        [0.2752, 0.3250, 0.2418, 0.4503, 0.2646, 0.4341, 0.7078],
        [0.2067, 0.4203, 0.1969, 0.3793, 0.3143, 0.4225, 0.6587],
        [0.2568, 0.3065, 0.3810, 0.4369, 0.3114, 0.2845, 0.6558],
        [0.2090, 0.3945, 0.2837, 0.4083, 0.3397, 0.3913, 0.6714],
        [0.2017, 0.3214, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.2012, 0.3304, 0.2819, 0.4037, 0.3139, 0.4026, 0.7276],
        [0.1732, 0.3719, 0.2311, 0.3321, 0.2730, 0.3543, 0.7215],
        [0.1947, 0.4858, 0.2489, 0.3480, 0.3449, 0.4216, 0.6883],
        [0.1827, 0.3896, 0.2889, 0.4377, 0.2348, 0.4080, 0.7000],
        [0.2450, 0.3223, 0.3895, 0.4391, 0.2712, 0.3289, 0.7249],
        [0.2252, 0.4405, 0.3021, 0.4208, 0.3907, 0.4725, 0.6948],
        [0.3048, 0.4599, 0.4258, 0.4672, 0.4413, 0.4240, 0.6441],
        [0.2754, 0.3480, 0.4021, 0.4496, 0.3604, 0.3565, 0.6798],
        [0.1593, 0.5371, 0.3751, 0.4003, 0.4054, 0.5107, 0.7095],
        [0.1947, 0.4858, 0.2489, 0.3480, 0.3449, 0.4216, 0.6883],
        [0.1964, 0.4412, 0.2027, 0.3840, 0.2739, 0.4765, 0.7274],
        [0.2686, 0.3317, 0.4546, 0.5592, 0.2697, 0.3412, 0.6318],
        [0.2945, 0.4712, 0.3627, 0.5494, 0.3155, 0.4415, 0.5801],
        [0.1478, 0.4556, 0.2969, 0.4360, 0.2816, 0.4924, 0.7260],
        [0.1732, 0.3719, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.3439, 0.3007, 0.4483, 0.5412, 0.2853, 0.3029, 0.6465],
        [0.2556, 0.3249, 0.3823, 0.4583, 0.3115, 0.2994, 0.6556],
        [0.1419, 0.3911, 0.2955, 0.4342, 0.2587, 0.5065, 0.7757],
        [0.3630, 0.3592, 0.3543, 0.5159, 0.3071, 0.4015, 0.6580],
        [0.2680, 0.3416, 0.4555, 0.5699, 0.2698, 0.3493, 0.6315],
        [0.1376, 0.4827, 0.1628, 0.3207, 0.2997, 0.4835, 0.7350],
        [0.2972, 0.4502, 0.4796, 0.5845, 0.3412, 0.4142, 0.5937],
        [0.1454, 0.5015, 0.2081, 0.4250, 0.2590, 0.5404, 0.7141],
        [0.1474, 0.4694, 0.2978, 0.4495, 0.2818, 0.5036, 0.7257],
        [0.1519, 0.4847, 0.2548, 0.3423, 0.3745, 0.5183, 0.7660],
        [0.1498, 0.5168, 0.1748, 0.3203, 0.3478, 0.5550, 0.7555],
        [0.1529, 0.4935, 0.2026, 0.4335, 0.2981, 0.4974, 0.6437],
        [0.1828, 0.3385, 0.1830, 0.3909, 0.2466, 0.3782, 0.6933],
        [0.2416, 0.3610, 0.2840, 0.4252, 0.2491, 0.3705, 0.7130],
        [0.1604, 0.5035, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.2359, 0.4763, 0.3707, 0.5491, 0.3443, 0.5433, 0.6715],
        [0.2542, 0.3262, 0.2284, 0.4860, 0.2245, 0.3928, 0.6840],
        [0.3032, 0.4614, 0.2618, 0.4951, 0.3356, 0.5272, 0.6731],
        [0.3664, 0.3353, 0.4703, 0.5463, 0.3324, 0.3709, 0.6705],
        [0.2138, 0.5246, 0.3044, 0.4911, 0.3440, 0.4574, 0.5888],
        [0.1299, 0.3752, 0.2795, 0.4511, 0.2193, 0.4485, 0.7556],
        [0.1816, 0.4218, 0.2915, 0.4701, 0.2356, 0.4341, 0.6988],
        [0.2184, 0.4453, 0.3512, 0.5521, 0.2965, 0.4739, 0.6471],
        [0.2542, 0.3262, 0.2284, 0.4860, 0.2245, 0.3928, 0.6840],
        [0.1601, 0.5151, 0.3173, 0.4602, 0.3289, 0.5837, 0.7462],
        [0.3399, 0.3385, 0.3361, 0.5273, 0.2627, 0.3429, 0.6326],
        [0.2076, 0.4266, 0.2859, 0.4404, 0.3404, 0.4174, 0.6706],
        [0.0975, 0.4351, 0.2435, 0.3705, 0.2841, 0.5159, 0.7819],
        [0.2935, 0.4937, 0.3647, 0.5710, 0.3162, 0.4593, 0.5792],
        [0.2245, 0.4574, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.1953, 0.4836, 0.2058, 0.4235, 0.2754, 0.5098, 0.7256],
        [0.1968, 0.4668, 0.3111, 0.4804, 0.2782, 0.5141, 0.7204],
        [0.0889, 0.4246, 0.2304, 0.3917, 0.2427, 0.4620, 0.7617],
        [0.1545, 0.4908, 0.2939, 0.4859, 0.3244, 0.4831, 0.6550],
        [0.1578, 0.5641, 0.2252, 0.4516, 0.3049, 0.6313, 0.7342],
        [0.1585, 0.5712, 0.3788, 0.4327, 0.4070, 0.5377, 0.7080],
        [0.1910, 0.3686, 0.2920, 0.4274, 0.2748, 0.4714, 0.7857],
        [0.1488, 0.4113, 0.2916, 0.4703, 0.2992, 0.4858, 0.7128],
        [0.2062, 0.4589, 0.3038, 0.4893, 0.3190, 0.4711, 0.6507],
        [0.2885, 0.5226, 0.3246, 0.4557, 0.3678, 0.5212, 0.7015],
        [0.1227, 0.3740, 0.2248, 0.3593, 0.2569, 0.4057, 0.7735],
        [0.2002, 0.3613, 0.2850, 0.4361, 0.3153, 0.4289, 0.7262],
        [0.1720, 0.4204, 0.2352, 0.3770, 0.2749, 0.3916, 0.7193],
        [0.1980, 0.4462, 0.2943, 0.4427, 0.2988, 0.4687, 0.7372],
        [0.3434, 0.3155, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.1920, 0.4045, 0.2378, 0.5500, 0.2135, 0.4720, 0.6669],
        [0.3625, 0.3830, 0.3577, 0.5400, 0.3087, 0.4203, 0.6562],
        [0.1600, 0.5388, 0.3206, 0.4822, 0.3307, 0.6005, 0.7446],
        [0.1371, 0.5352, 0.1669, 0.3652, 0.3029, 0.5230, 0.7318],
        [0.1279, 0.4484, 0.1981, 0.4667, 0.2025, 0.5175, 0.7419],
        [0.1298, 0.4090, 0.2841, 0.4838, 0.2214, 0.4744, 0.7532],
        [0.1494, 0.5601, 0.1784, 0.3573, 0.3508, 0.5871, 0.7530],
        [0.1267, 0.4928, 0.2435, 0.4282, 0.2617, 0.4619, 0.7040],
        [0.1936, 0.5429, 0.2544, 0.3990, 0.3480, 0.4650, 0.6851],
        [0.3007, 0.5233, 0.3184, 0.4724, 0.4150, 0.4845, 0.6287],
        [0.1395, 0.4734, 0.2112, 0.4581, 0.2399, 0.5818, 0.7626],
        [0.2098, 0.5678, 0.2700, 0.3907, 0.3989, 0.5299, 0.7085],
        [0.1524, 0.5457, 0.2075, 0.4824, 0.3013, 0.5368, 0.6399],
        [0.1563, 0.6213, 0.2768, 0.4266, 0.3811, 0.5884, 0.6944],
        [0.1968, 0.4812, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.1970, 0.4964, 0.3158, 0.5074, 0.2809, 0.5348, 0.7176],
        [0.1490, 0.4404, 0.2962, 0.4975, 0.3020, 0.5068, 0.7100],
        [0.1948, 0.3806, 0.3366, 0.5801, 0.2345, 0.4396, 0.6784],
        [0.1817, 0.4742, 0.2991, 0.5186, 0.2394, 0.4718, 0.6942],
        [0.1228, 0.4085, 0.2295, 0.3902, 0.2600, 0.4304, 0.7705],
        [0.1321, 0.4729, 0.1673, 0.3661, 0.2806, 0.5381, 0.7794],
        [0.2157, 0.5243, 0.2572, 0.5702, 0.2766, 0.5447, 0.6294],
        [0.2718, 0.4752, 0.4192, 0.4976, 0.3457, 0.4262, 0.6889],
        [0.2718, 0.4752, 0.4192, 0.4976, 0.3457, 0.4262, 0.6889],
        [0.1403, 0.4928, 0.3621, 0.4499, 0.3321, 0.4942, 0.7369],
        [0.1565, 0.6354, 0.2792, 0.4399, 0.3830, 0.5983, 0.6928],
        [0.1547, 0.5207, 0.2986, 0.5130, 0.3274, 0.5041, 0.6519],
        [0.1682, 0.5428, 0.3152, 0.5018, 0.3766, 0.5667, 0.6770],
        [0.2184, 0.4811, 0.3569, 0.5843, 0.2995, 0.4996, 0.6437],
        [0.2331, 0.5464, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.1985, 0.4826, 0.3004, 0.4754, 0.3027, 0.4936, 0.7335],
        [0.2972, 0.4952, 0.4875, 0.6236, 0.3453, 0.4457, 0.5891],
        [0.2054, 0.5207, 0.2061, 0.4724, 0.3210, 0.4976, 0.6513],
        [0.2129, 0.5461, 0.3764, 0.4231, 0.4289, 0.4990, 0.7187],
        [0.2604, 0.4503, 0.3104, 0.4786, 0.2975, 0.4814, 0.7298],
        [0.2334, 0.5587, 0.2747, 0.5700, 0.3236, 0.6137, 0.6535],
        [0.2848, 0.4611, 0.3704, 0.5979, 0.2960, 0.4954, 0.6375],
        [0.2772, 0.3554, 0.3479, 0.5379, 0.2915, 0.4471, 0.7155],
        [0.1935, 0.4386, 0.4015, 0.5552, 0.3016, 0.3952, 0.6336],
        [0.1377, 0.5712, 0.1712, 0.3960, 0.3074, 0.5470, 0.7277],
        [0.1232, 0.4263, 0.2324, 0.4057, 0.2622, 0.4420, 0.7685],
        [0.1891, 0.4486, 0.2098, 0.4485, 0.2571, 0.5434, 0.7715],
        [0.3734, 0.4797, 0.3639, 0.5715, 0.3366, 0.4296, 0.5909],
        [0.3046, 0.4953, 0.4314, 0.5005, 0.4445, 0.4497, 0.6410],
        [0.1499, 0.5899, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.3041, 0.5064, 0.2687, 0.5359, 0.3409, 0.5576, 0.6679],
        [0.1447, 0.6491, 0.2708, 0.4836, 0.3392, 0.5594, 0.6626],
        [0.1966, 0.5442, 0.2143, 0.4772, 0.2825, 0.5498, 0.7186],
        [0.2194, 0.5061, 0.3626, 0.6054, 0.3032, 0.5152, 0.6397],
        [0.2367, 0.5220, 0.3794, 0.5894, 0.3497, 0.5738, 0.6662],
        [0.2978, 0.5048, 0.4901, 0.6314, 0.3470, 0.4514, 0.5873],
        [0.2108, 0.6031, 0.2766, 0.4222, 0.4045, 0.5532, 0.7038],
        [0.2926, 0.5095, 0.4413, 0.4971, 0.3981, 0.4962, 0.7109],
        [0.2100, 0.4699, 0.4230, 0.5523, 0.3507, 0.4623, 0.6576],
        [0.2252, 0.5027, 0.3112, 0.4784, 0.3970, 0.5172, 0.6892],
        [0.1942, 0.4541, 0.4054, 0.5687, 0.3041, 0.4043, 0.6308],
        [0.2061, 0.5361, 0.2087, 0.4860, 0.3236, 0.5070, 0.6487],
        [0.2895, 0.5586, 0.3313, 0.4882, 0.3727, 0.5450, 0.6972],
        [0.1556, 0.5516, 0.3050, 0.5403, 0.3322, 0.5234, 0.6469],
        [0.2108, 0.6031, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.3024, 0.5594, 0.3262, 0.5049, 0.4213, 0.5074, 0.6228],
        [0.2845, 0.5025, 0.2575, 0.5629, 0.2973, 0.5057, 0.6390],
        [0.2353, 0.5749, 0.4463, 0.5591, 0.4309, 0.5239, 0.6210],
        [0.1595, 0.6366, 0.2376, 0.5193, 0.3154, 0.6754, 0.7247],
        [0.3747, 0.4981, 0.3686, 0.5871, 0.3400, 0.4403, 0.5873],
        [0.1544, 0.6170, 0.2196, 0.5472, 0.3124, 0.5821, 0.6280],
        [0.1544, 0.6170, 0.2196, 0.5472, 0.3124, 0.5821, 0.6280],
        [0.1469, 0.6246, 0.2254, 0.5384, 0.2721, 0.6232, 0.7002],
        [0.3676, 0.3683, 0.4783, 0.5783, 0.3371, 0.3937, 0.6659],
        [0.2434, 0.4614, 0.3014, 0.5190, 0.2595, 0.4385, 0.7016],
        [0.2328, 0.6250, 0.3366, 0.5528, 0.4054, 0.5740, 0.6047],
        [0.1390, 0.6063, 0.1770, 0.4271, 0.3139, 0.5682, 0.7219],
        [0.1595, 0.6366, 0.2376, 0.5193, 0.3154, 0.6754, 0.7247],
        [0.3780, 0.4461, 0.4812, 0.5933, 0.3639, 0.3911, 0.6038],
        [0.2201, 0.5183, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.2910, 0.5758, 0.3363, 0.5038, 0.3768, 0.5549, 0.6937],
        [0.1426, 0.5528, 0.3780, 0.5033, 0.3435, 0.5302, 0.7274],
        [0.2142, 0.5829, 0.2320, 0.4816, 0.3325, 0.6200, 0.7374],
        [0.1685, 0.6422, 0.2350, 0.5407, 0.3625, 0.6440, 0.6522],
        [0.1465, 0.6804, 0.2798, 0.5149, 0.3472, 0.5791, 0.6550],
        [0.1128, 0.6466, 0.2812, 0.4748, 0.3734, 0.6462, 0.7409],
        [0.1239, 0.5347, 0.1695, 0.4487, 0.2522, 0.5253, 0.7468],
        [0.1789, 0.4288, 0.2936, 0.5137, 0.2451, 0.4616, 0.7552],
        [0.1415, 0.5701, 0.2585, 0.4465, 0.3405, 0.5263, 0.7324],
        [0.2072, 0.6340, 0.3333, 0.5756, 0.3162, 0.5677, 0.6491],
        [0.1036, 0.6377, 0.2683, 0.4967, 0.3266, 0.5939, 0.7166],
        [0.1024, 0.6867, 0.1881, 0.4927, 0.3046, 0.6430, 0.7019],
        [0.1024, 0.6867, 0.1881, 0.4927, 0.3046, 0.6430, 0.7019],
        [0.2113, 0.5039, 0.2680, 0.6066, 0.2634, 0.5827, 0.6789],
        [0.1941, 0.5383, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.2870, 0.5254, 0.2639, 0.5828, 0.3030, 0.5185, 0.6329],
        [0.1252, 0.5542, 0.1739, 0.4663, 0.2571, 0.5363, 0.7422],
        [0.1999, 0.5871, 0.2246, 0.5162, 0.2923, 0.5741, 0.7094],
        [0.2369, 0.5912, 0.4526, 0.5739, 0.4359, 0.5333, 0.6164],
        [0.1802, 0.4428, 0.2982, 0.5264, 0.2485, 0.4695, 0.7520],
        [0.1425, 0.5839, 0.2628, 0.4591, 0.3447, 0.5341, 0.7290],
        [0.2911, 0.4502, 0.4963, 0.6382, 0.3270, 0.4687, 0.6443],
        [0.2245, 0.6531, 0.3517, 0.5639, 0.3656, 0.6271, 0.6736],
        [0.2595, 0.4379, 0.2502, 0.5913, 0.2399, 0.4670, 0.6654],
        [0.2109, 0.5616, 0.3279, 0.5810, 0.3371, 0.5354, 0.6323],
        [0.3691, 0.3791, 0.4826, 0.5882, 0.3402, 0.3999, 0.6630],
        [0.2113, 0.5221, 0.3062, 0.5264, 0.3564, 0.4781, 0.6552],
        [0.3004, 0.5312, 0.4995, 0.6527, 0.3537, 0.4663, 0.5805],
        [0.2801, 0.3885, 0.3582, 0.5688, 0.2988, 0.4673, 0.7087],
        [0.1911, 0.5510, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.2164, 0.5883, 0.3907, 0.4615, 0.4409, 0.5238, 0.7095],
        [0.1328, 0.6331, 0.2777, 0.5554, 0.2890, 0.5482, 0.6760],
        [0.2275, 0.6066, 0.4646, 0.5723, 0.3917, 0.5800, 0.6874],
        [0.2236, 0.5514, 0.3785, 0.6430, 0.3150, 0.5409, 0.6275],
        [0.3098, 0.4796, 0.3771, 0.5647, 0.3717, 0.5216, 0.6768],
        [0.1892, 0.5077, 0.2115, 0.5478, 0.2720, 0.4893, 0.6652],
        [0.1461, 0.5354, 0.3279, 0.5659, 0.2802, 0.5995, 0.7568],
        [0.2141, 0.5148, 0.4396, 0.5916, 0.3632, 0.4879, 0.6460],
        [0.1941, 0.5041, 0.3749, 0.4727, 0.3650, 0.4739, 0.7372],
        [0.2159, 0.4703, 0.3754, 0.6283, 0.2899, 0.5432, 0.6881],
        [0.1941, 0.5041, 0.3749, 0.4727, 0.3650, 0.4739, 0.7372],
        [0.3700, 0.3842, 0.4850, 0.5928, 0.3420, 0.4028, 0.6613],
        [0.2631, 0.3923, 0.3491, 0.6019, 0.2615, 0.4201, 0.6784],
        [0.3468, 0.4388, 0.3625, 0.6195, 0.2798, 0.4056, 0.6128],
        [0.1927, 0.5640, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.1438, 0.5377, 0.3156, 0.6133, 0.2855, 0.5144, 0.6578],
        [0.3071, 0.5905, 0.3383, 0.5340, 0.4329, 0.5257, 0.6125],
        [0.2814, 0.4646, 0.2693, 0.5853, 0.2857, 0.5327, 0.6860],
        [0.2380, 0.6634, 0.3530, 0.5902, 0.4205, 0.5974, 0.5908],
        [0.1629, 0.7208, 0.3080, 0.5283, 0.4101, 0.6525, 0.6698],
        [0.2898, 0.5274, 0.4319, 0.5599, 0.4077, 0.4190, 0.5999],
        [0.1021, 0.6631, 0.2019, 0.5263, 0.2979, 0.6732, 0.7400],
        [0.3490, 0.4486, 0.3675, 0.6280, 0.2836, 0.4113, 0.6086],
        [0.1808, 0.5744, 0.2720, 0.5140, 0.3063, 0.4854, 0.6892],
        [0.2015, 0.5411, 0.2725, 0.6659, 0.2388, 0.5546, 0.6355],
        [0.2906, 0.5455, 0.2718, 0.6005, 0.3106, 0.5303, 0.6253],
        [0.1354, 0.5895, 0.3837, 0.5675, 0.3147, 0.5018, 0.6876],
        [0.2516, 0.4533, 0.4252, 0.5645, 0.2931, 0.4136, 0.7036],
        [0.1972, 0.4693, 0.3194, 0.5201, 0.2953, 0.5350, 0.7694],
        [0.1462, 0.5909, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.1478, 0.6011, 0.4020, 0.5487, 0.3635, 0.5589, 0.7113],
        [0.2971, 0.5413, 0.4551, 0.5262, 0.4095, 0.5145, 0.7021],
        [0.2704, 0.4613, 0.4415, 0.5418, 0.3380, 0.4677, 0.7284],
        [0.1535, 0.6756, 0.4049, 0.5640, 0.3913, 0.5564, 0.6530],
        [0.2704, 0.4613, 0.4415, 0.5418, 0.3380, 0.4677, 0.7284],
        [0.2174, 0.5330, 0.4505, 0.6080, 0.3724, 0.4990, 0.6378],
        [0.3716, 0.4568, 0.3831, 0.6064, 0.3278, 0.4655, 0.6370],
        [0.3112, 0.5536, 0.2851, 0.5784, 0.3569, 0.5844, 0.6532],
        [0.2263, 0.6314, 0.2907, 0.6630, 0.3053, 0.6082, 0.5983],
        [0.2946, 0.5366, 0.3999, 0.6610, 0.3178, 0.5395, 0.6149],
        [0.2964, 0.6047, 0.3499, 0.5315, 0.3893, 0.5720, 0.6833],
        [0.1580, 0.6174, 0.2869, 0.4610, 0.4049, 0.6034, 0.7440],
        [0.2182, 0.6615, 0.2991, 0.4796, 0.4274, 0.5890, 0.6855],
        [0.1457, 0.5506, 0.3230, 0.6249, 0.2918, 0.5224, 0.6515],
        [0.2529, 0.5268, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.3543, 0.4653, 0.3790, 0.6429, 0.2925, 0.4217, 0.5991],
        [0.2053, 0.6086, 0.3445, 0.6527, 0.3187, 0.5151, 0.5761],
        [0.1682, 0.7009, 0.2658, 0.5858, 0.3442, 0.7115, 0.7004],
        [0.0980, 0.6905, 0.2096, 0.5866, 0.2762, 0.6462, 0.6969],
        [0.2809, 0.6127, 0.3458, 0.5699, 0.3509, 0.5280, 0.6477],
        [0.2193, 0.6061, 0.3529, 0.6222, 0.3595, 0.5630, 0.6111],
        [0.2673, 0.4617, 0.4289, 0.5888, 0.3451, 0.3828, 0.6224],
        [0.1667, 0.7367, 0.3208, 0.5480, 0.4232, 0.6640, 0.6591],
        [0.1875, 0.5553, 0.2354, 0.5761, 0.2523, 0.5564, 0.7165],
        [0.1554, 0.7387, 0.3129, 0.5804, 0.3795, 0.6197, 0.6257],
        [0.1058, 0.6283, 0.2979, 0.5470, 0.3312, 0.6361, 0.7448],
        [0.1667, 0.7367, 0.3208, 0.5480, 0.4232, 0.6640, 0.6591],
        [0.2327, 0.5558, 0.3335, 0.5277, 0.4184, 0.5484, 0.6716],
        [0.2193, 0.6061, 0.3529, 0.6222, 0.3595, 0.5630, 0.6111],
        [0.2222, 0.5638, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.1906, 0.5655, 0.2429, 0.5867, 0.2593, 0.5631, 0.7097],
        [0.3093, 0.6288, 0.4153, 0.6873, 0.3546, 0.5462, 0.5390],
        [0.2013, 0.5373, 0.3981, 0.5053, 0.3856, 0.4948, 0.7218],
        [0.1358, 0.6280, 0.2050, 0.5396, 0.2934, 0.5826, 0.7095],
        [0.3574, 0.4722, 0.3854, 0.6494, 0.2976, 0.4262, 0.5937],
        [0.1354, 0.5620, 0.2832, 0.5304, 0.3086, 0.5229, 0.7294],
        [0.2584, 0.4766, 0.4439, 0.5870, 0.3073, 0.4282, 0.6909],
        [0.3148, 0.4963, 0.3886, 0.5806, 0.3822, 0.5320, 0.6680],
        [0.2081, 0.5517, 0.4562, 0.6541, 0.3428, 0.4615, 0.5921],
        [0.2128, 0.4851, 0.3289, 0.5527, 0.3534, 0.5076, 0.6935],
        [0.1702, 0.6482, 0.3646, 0.5857, 0.3679, 0.6645, 0.7151],
        [0.2203, 0.5652, 0.3314, 0.5676, 0.3808, 0.5049, 0.6336],
        [0.2030, 0.4931, 0.3362, 0.5437, 0.3098, 0.5500, 0.7583],
        [0.2245, 0.6346, 0.2564, 0.5334, 0.3593, 0.6502, 0.7163],
        [0.2133, 0.5535, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.1914, 0.5486, 0.3995, 0.5481, 0.3521, 0.4526, 0.6843],
        [0.1636, 0.5750, 0.3557, 0.6209, 0.3529, 0.5877, 0.6643],
        [0.1149, 0.7689, 0.2351, 0.5929, 0.3605, 0.6991, 0.6520],
        [0.1542, 0.6252, 0.4270, 0.5753, 0.3851, 0.5753, 0.6941],
        [0.3179, 0.5689, 0.2979, 0.5944, 0.3700, 0.5943, 0.6415],
        [0.3125, 0.6340, 0.4224, 0.6928, 0.3605, 0.5500, 0.5330],
        [0.2856, 0.4925, 0.5178, 0.7014, 0.3109, 0.4455, 0.5867],
        [0.2025, 0.6338, 0.3716, 0.6630, 0.2931, 0.5697, 0.6376],
        [0.1931, 0.5045, 0.3376, 0.5858, 0.2799, 0.5078, 0.7239],
        [0.1723, 0.6533, 0.3713, 0.5921, 0.3740, 0.6678, 0.7103],
        [0.2055, 0.4989, 0.3428, 0.5504, 0.3155, 0.5538, 0.7540],
        [0.2461, 0.6255, 0.4795, 0.6082, 0.4600, 0.5556, 0.5955],
        [0.2216, 0.6381, 0.4820, 0.6338, 0.3711, 0.5520, 0.6359],
        [0.1610, 0.7528, 0.3314, 0.6004, 0.3976, 0.6313, 0.6095],
        [0.2274, 0.5786, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.2283, 0.6838, 0.3237, 0.5083, 0.4532, 0.6052, 0.6650],
        [0.1062, 0.7192, 0.2402, 0.6248, 0.3088, 0.6670, 0.6658],
        [0.4100, 0.5494, 0.4102, 0.6050, 0.4111, 0.5208, 0.5952],
        [0.1629, 0.7018, 0.4393, 0.5972, 0.4217, 0.5764, 0.6269],
        [0.2281, 0.5765, 0.3558, 0.5339, 0.3855, 0.5984, 0.7289],
        [0.2166, 0.6329, 0.3751, 0.6792, 0.3450, 0.5325, 0.5494],
        [0.1965, 0.6234, 0.3147, 0.5682, 0.3470, 0.5188, 0.6523],
        [0.3649, 0.4828, 0.4001, 0.6610, 0.3092, 0.4332, 0.5815],
        [0.1123, 0.6521, 0.3262, 0.5767, 0.3579, 0.6519, 0.7239],
        [0.2154, 0.5831, 0.3522, 0.5710, 0.3475, 0.5541, 0.6956],
        [0.2914, 0.5681, 0.4237, 0.7168, 0.3045, 0.5108, 0.5529],
        [0.2957, 0.4994, 0.2973, 0.6207, 0.3118, 0.5550, 0.6612],
        [0.1179, 0.7746, 0.2450, 0.6032, 0.3717, 0.7037, 0.6419],
        [0.2258, 0.5753, 0.3448, 0.5800, 0.3935, 0.5118, 0.6221],
        [0.1644, 0.7579, 

       device='cuda:0', grad_fn=<SigmoidBackward>)
tensor([[0.1719, 0.6533, 0.2861, 0.6479, 0.3580, 0.6536, 0.6215],
        [0.1588, 0.6512, 0.3165, 0.5342, 0.3994, 0.5785, 0.6852],
        [0.4084, 0.4792, 0.5140, 0.5943, 0.4269, 0.4593, 0.6203],
        [0.1673, 0.6674, 0.3847, 0.6400, 0.3509, 0.6321, 0.6627],
        [0.1531, 0.5754, 0.3143, 0.5196, 0.3717, 0.5814, 0.7400],
        [0.3957, 0.5588, 0.4125, 0.6442, 0.3773, 0.4773, 0.5504],
        [0.3066, 0.6250, 0.3664, 0.6039, 0.4235, 0.4997, 0.5451],
        [0.3236, 0.5751, 0.3080, 0.6031, 0.3801, 0.5984, 0.6323],
        [0.2195, 0.6935, 0.3297, 0.5530, 0.4222, 0.5642, 0.6197],
        [0.1771, 0.6607, 0.3864, 0.6034, 0.3873, 0.6727, 0.6995],
        [0.1622, 0.6991, 0.3512, 0.6036, 0.3906, 0.6420, 0.6531],
        [0.3236, 0.5751, 0.3080, 0.6031, 0.3801, 0.5984, 0.6323],
        [0.2184, 0.5866, 0.3599, 0.5766, 0.3542, 0.5565, 0.6897],
        [0.1885, 0.7158, 0.2896, 0.6254, 0.4229, 0.6905, 0.5980],
        [0.2024, 0.5864, 