In [1]:
import torch
import torchvision
from torchvision import transforms, datasets, models
import matplotlib.pyplot as plt
import torch.optim as optim


import torch.nn as nn
import torch.nn.functional as F



import os 
import time
import cv2
import numpy as np
from tqdm.notebook import tqdm
import pandas as pd

rebuild_data = False

In [2]:
if torch.cuda.is_available():
    device = torch.device("cuda: 0")
else:
    device = torch.device("cpu")
    
#i could assign specific layers to one gpu 

torch.cuda.device_count() #but i have only one :P
    

1

In [3]:
x = torch.empty(5,3)
print(x)
x.shape
x.shape

tensor([[9.6428e-39, 1.1112e-38, 9.5511e-39],
        [1.0102e-38, 1.0286e-38, 1.0194e-38],
        [9.6429e-39, 9.2755e-39, 9.1837e-39],
        [9.3674e-39, 1.0745e-38, 1.0653e-38],
        [9.5510e-39, 1.0561e-38, 1.0194e-38]])


torch.Size([5, 3])

In [4]:
x = torch.rand(5,3)

In [5]:
print(x)

tensor([[0.9999, 0.0108, 0.4937],
        [0.6717, 0.5771, 0.5992],
        [0.9908, 0.4062, 0.5244],
        [0.3613, 0.2407, 0.7820],
        [0.9292, 0.4248, 0.4336]])


In [6]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
x = torch.tensor([5.5, 3])

In [8]:
x.shape

torch.Size([2])

In [9]:
x.view(-1,2).shape

torch.Size([1, 2])

In [10]:
x = x.new_ones(5, 3)

In [11]:
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [12]:
x = torch.randn_like(x)
print(type(x[0][0]))

<class 'torch.Tensor'>


In [13]:
x = torch.ones(2, 2, requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [14]:
y = x + 2

In [15]:
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [16]:
z = y /2 * 5

In [17]:
print(z)

tensor([[7.5000, 7.5000],
        [7.5000, 7.5000]], grad_fn=<MulBackward0>)


In [18]:
z += z
print(z)

tensor([[15., 15.],
        [15., 15.]], grad_fn=<AddBackward0>)


In [19]:
x.requires_grad

True

In [20]:
q = torch.ones(1,4)

In [21]:
q.requires_grad

False

In [22]:
print(q.grad_fn)

None


In [23]:
z = x + 2


In [24]:
z = z.sum()

In [25]:
z.backward()

In [26]:
x.grad

tensor([[1., 1.],
        [1., 1.]])

In [27]:
v = torch.zeros(1,2)
print(v)

tensor([[0., 0.]])


In [28]:
a = torch.ones(1,2, requires_grad=True) * 2
b = a * a
v += b
print(a.grad)

C:\Users\G7\Anaconda3\lib\site-packages\torch\tensor.py:746: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  warnings.warn("The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad "


None


In [29]:
c = torch.zeros(1,2)
v.backward(c)
a.grad